# -*- coding: utf-8 -*-
"""
GPT_205_SEM_3B1_promptstar_encoding_ablation.py

SEM-3B.1: Prompt* Encoding Ablation
-----------------------------------

Goal:
    Diagnose why SEM-3B did not pass.

Hypothesis:
    SEM-3C.0b showed family center μ_F exists and beats hand-written canonical seed.
    SEM-3B failed because the mapping:
        μ_F -> natural language Prompt*
    was too weak.

This script tests three encoding strategies:
    A. previous Prompt* templates from SEM-3C.0b:
       - natural_prompt_star
       - structured_prompt_star
       - compressed_prompt_star

    B. μF-nearest exemplar prompt:
       - pick the original prompt within each family closest to μ_F in the selected feature block.

    C. μF-nearest exemplar + distilled structure:
       - combine the nearest real prompt with extracted family common structure.

    D. canonical minimal seed:
       - hand-written canonical seed from SEM-3A dataset.

Then forward all candidate prompts and compare regenerated trajectories to original prompts.

Interpretation:
    If nearest exemplar works but Prompt* fails:
        language prompt construction is the bottleneck.
    If nearest exemplar also fails:
        μ_F may be a statistical center not realizable by one prompt.
    If distilled nearest improves:
        Prompt* should be generated by exemplar-anchored structure distillation.

Inputs:
    sem3a_outputs/
      sem3a_dataset.csv
      sem3a_features.csv

    sem3c0b_outputs/
      sem3c0b_family_center_features.csv
      sem3c0b_prompt_star_candidates.csv
      sem3c0b_family_member_residuals.csv

Outputs:
    sem3b1_outputs/
      sem3b1_candidate_dataset.csv
      sem3b1_candidate_features.csv
      sem3b1_pairwise_regeneration.csv
      sem3b1_strategy_summary.csv
      sem3b1_family_summary.csv
      sem3b1_results_summary.json

Run:
    python GPT_205_SEM_3B1_promptstar_encoding_ablation.py
"""

import json
import random
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import List, Tuple, Dict, Any

import numpy as np
import pandas as pd

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from scipy.stats import ttest_rel, wilcoxon


# ============================================================
# CONFIG
# ============================================================

@dataclass
class CFG:
    MODEL_PATH: str = r"D:\model\models--Qwen--Qwen2.5-1.5B-Instruct\main"

    SEM3A_DIR: str = "./sem3a_outputs"
    SEM3C0B_DIR: str = "./sem3c0b_outputs"
    OUTPUT_DIR: str = "./sem3b1_outputs"

    SEM3A_DATASET: str = "sem3a_dataset.csv"
    SEM3A_FEATURES: str = "sem3a_features.csv"

    FAMILY_CENTERS: str = "sem3c0b_family_center_features.csv"
    PROMPTSTAR_CANDIDATES: str = "sem3c0b_prompt_star_candidates.csv"
    MEMBER_RESIDUALS: str = "sem3c0b_family_member_residuals.csv"

    TOPK_LIST: Tuple[int, ...] = (100, 500)
    LAYERS: Tuple[int, ...] = tuple(range(0, 26))
    BATCH_SIZE: int = 4
    MAX_LENGTH: int = 192
    CENTER_PCA_DIM: int = 16
    DEVICE: str = "cuda" if torch.cuda.is_available() else "cpu"
    DTYPE: str = "auto"
    RANDOM_SEED: int = 42

    MAIN_BLOCK: str = "center_pca"
    REUSE_CANDIDATE_FEATURES_IF_EXISTS: bool = True


cfg = CFG()


# ============================================================
# UTILS
# ============================================================

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def ensure_dir(path: str):
    Path(path).mkdir(parents=True, exist_ok=True)


def json_dump(obj: Any, path: Path):
    def convert(o):
        if isinstance(o, (np.integer,)):
            return int(o)
        if isinstance(o, (np.floating,)):
            return float(o)
        if isinstance(o, np.ndarray):
            return o.tolist()
        if isinstance(o, Path):
            return str(o)
        if isinstance(o, float) and np.isnan(o):
            return None
        return str(o)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2, default=convert)


def get_torch_dtype(dtype_name: str):
    if dtype_name == "float16":
        return torch.float16
    if dtype_name == "bfloat16":
        return torch.bfloat16
    if dtype_name == "float32":
        return torch.float32
    return "auto"


def cosine_np(a, b, eps=1e-9):
    a = np.asarray(a)
    b = np.asarray(b)
    na = np.linalg.norm(a)
    nb = np.linalg.norm(b)
    if na < eps or nb < eps:
        return 0.0
    return float(np.dot(a, b) / (na * nb))


def jaccard(a: set, b: set):
    if not a and not b:
        return 1.0
    u = len(a | b)
    return len(a & b) / u if u else 0.0


# ============================================================
# MODEL + FEATURE EXTRACTION
# ============================================================

def load_model_and_tokenizer(cfg: CFG):
    print(f"[SEM-3B.1] Loading model: {cfg.MODEL_PATH}")
    dtype = get_torch_dtype(cfg.DTYPE)

    tokenizer = AutoTokenizer.from_pretrained(
        cfg.MODEL_PATH,
        trust_remote_code=True,
        local_files_only=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        cfg.MODEL_PATH,
        trust_remote_code=True,
        local_files_only=True,
        torch_dtype=dtype,
        device_map="auto" if cfg.DEVICE == "cuda" else None,
    )
    if cfg.DEVICE != "cuda":
        model.to(cfg.DEVICE)
    model.eval()
    return model, tokenizer


def get_lm_head_weight(model):
    if hasattr(model, "get_output_embeddings") and model.get_output_embeddings() is not None:
        return model.get_output_embeddings().weight
    raise RuntimeError("Cannot find output embedding / lm_head weight.")


@torch.no_grad()
def extract_batch(prompts: List[str], model, tokenizer, cfg: CFG):
    enc = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=cfg.MAX_LENGTH,
    )
    enc = {k: v.to(model.device) for k, v in enc.items()}

    out = model(
        **enc,
        output_hidden_states=True,
        use_cache=False,
        return_dict=True,
    )

    hidden_states = out.hidden_states
    W = get_lm_head_weight(model).to(model.device)
    last_pos = enc["attention_mask"].sum(dim=1) - 1

    scalar_rows = []
    center_records = []

    for bi in range(len(prompts)):
        row = {}
        prev_center = {}
        prev_set = {}

        for layer in cfg.LAYERS:
            hs_index = layer + 1
            if hs_index >= len(hidden_states):
                continue

            h = hidden_states[hs_index][bi, last_pos[bi], :]
            logits = torch.matmul(h, W.T)

            for k in cfg.TOPK_LIST:
                vals, ids = torch.topk(logits, k=k, dim=-1)
                vals_np = vals.detach().float().cpu().numpy()
                ids_np = ids.detach().cpu().numpy().astype(np.int64)

                emb = W[ids].detach().float()
                center = emb.mean(dim=0)
                center_np = center.cpu().numpy()

                emb_norm = torch.nn.functional.normalize(emb, dim=-1)
                c_norm = torch.nn.functional.normalize(center.unsqueeze(0), dim=-1)
                cos = (emb_norm * c_norm).sum(dim=-1)
                spread = float((1.0 - cos).mean().detach().cpu())

                probs = torch.softmax(vals.float(), dim=-1)
                entropy = float((-(probs * torch.log(probs + 1e-12)).sum()).detach().cpu())

                id_set = set(ids_np.tolist())
                p = f"k{k}_L{layer}"

                row[f"{p}_spread"] = spread
                row[f"{p}_entropy"] = entropy
                row[f"{p}_gap"] = float(vals_np[0] - vals_np[-1])
                row[f"{p}_meanlogit"] = float(vals_np.mean())
                row[f"{p}_center_norm"] = float(np.linalg.norm(center_np))

                if k in prev_center:
                    row[f"{p}_center_shift_cosdist"] = 1.0 - cosine_np(prev_center[k], center_np)
                    row[f"{p}_center_shift_l2"] = float(np.linalg.norm(center_np - prev_center[k]))
                else:
                    row[f"{p}_center_shift_cosdist"] = 0.0
                    row[f"{p}_center_shift_l2"] = 0.0

                if k in prev_set:
                    jac = jaccard(prev_set[k], id_set)
                    row[f"{p}_jaccard_prev"] = jac
                    row[f"{p}_jaccard_dist_prev"] = 1.0 - jac
                else:
                    row[f"{p}_jaccard_prev"] = 1.0
                    row[f"{p}_jaccard_dist_prev"] = 0.0

                prev_center[k] = center_np
                prev_set[k] = id_set

                center_records.append({
                    "batch_index": bi,
                    "layer": layer,
                    "k": k,
                    "center": center_np,
                })

        scalar_rows.append(row)

    return scalar_rows, center_records


def extract_all_features(df: pd.DataFrame, model, tokenizer, cfg: CFG):
    prompts = df["prompt"].astype(str).tolist()
    all_scalar = []
    all_center_records = []

    for start in range(0, len(prompts), cfg.BATCH_SIZE):
        end = min(start + cfg.BATCH_SIZE, len(prompts))
        print(f"[SEM-3B.1] Extracting {start}:{end}/{len(prompts)}")
        scalar_rows, center_records = extract_batch(prompts[start:end], model, tokenizer, cfg)

        for i, r in enumerate(scalar_rows):
            r["row_id"] = int(df.iloc[start + i]["row_id"])
            all_scalar.append(r)

        for rec in center_records:
            rec["row_id"] = int(df.iloc[start + rec["batch_index"]]["row_id"])
            del rec["batch_index"]
            all_center_records.append(rec)

    scalar_df = pd.DataFrame(all_scalar)

    center_feature_rows = {int(rid): {"row_id": int(rid)} for rid in df["row_id"].values}
    for k in cfg.TOPK_LIST:
        for layer in cfg.LAYERS:
            recs = [r for r in all_center_records if r["k"] == k and r["layer"] == layer]
            if not recs:
                continue
            X = np.vstack([r["center"] for r in recs])
            n_comp = min(cfg.CENTER_PCA_DIM, X.shape[0], X.shape[1])
            pca = PCA(n_components=n_comp, random_state=cfg.RANDOM_SEED)
            Z = pca.fit_transform(StandardScaler().fit_transform(X))
            for rec, z in zip(recs, Z):
                rid = int(rec["row_id"])
                for j in range(n_comp):
                    center_feature_rows[rid][f"k{k}_L{layer}_centerPC{j+1}"] = float(z[j])

    center_df = pd.DataFrame(list(center_feature_rows.values())).fillna(0.0)
    return df.merge(scalar_df, on="row_id", how="left").merge(center_df, on="row_id", how="left")


# ============================================================
# FEATURE BLOCKS
# ============================================================

def get_feature_cols(df: pd.DataFrame, block: str):
    exclude = {
        "row_id", "row_type", "seed_family", "concept_star", "operator_star",
        "surface_id", "prompt", "candidate_type", "source_template_type",
        "operator_id", "common_structure", "source_row_id"
    }
    numeric = [c for c in df.columns if c not in exclude and pd.api.types.is_numeric_dtype(df[c])]

    if block == "all":
        return numeric
    if block == "scalar":
        return [c for c in numeric if "centerPC" not in c]
    if block == "center_pca":
        return [c for c in numeric if "centerPC" in c]
    if block == "transport":
        return [c for c in numeric if any(k in c for k in ["shift", "jaccard"])]
    if block == "init":
        return [c for c in numeric if any(f"_L{i}_" in c for i in range(0, 7))]
    if block == "mid":
        return [c for c in numeric if any(f"_L{i}_" in c for i in range(7, 20))]
    if block == "decision":
        return [c for c in numeric if any(f"_L{i}_" in c for i in range(20, 26))]
    raise ValueError(block)


def align_spaces(original_features: pd.DataFrame, candidate_features: pd.DataFrame, block: str):
    cols = sorted(set(get_feature_cols(original_features, block)) & set(get_feature_cols(candidate_features, block)))
    if not cols:
        return None, None, []
    combined = pd.concat(
        [
            original_features[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0),
            candidate_features[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0),
        ],
        axis=0,
    )
    scaler = StandardScaler()
    scaler.fit(combined.values.astype(np.float32))
    Xo = scaler.transform(original_features[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0).values.astype(np.float32))
    Xc = scaler.transform(candidate_features[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0).values.astype(np.float32))
    return Xo, Xc, cols


# ============================================================
# LOAD INPUTS AND BUILD CANDIDATES
# ============================================================

def load_inputs(cfg: CFG):
    sem3a_dir = Path(cfg.SEM3A_DIR)
    sem3c_dir = Path(cfg.SEM3C0B_DIR)

    dataset = pd.read_csv(sem3a_dir / cfg.SEM3A_DATASET)
    features = pd.read_csv(sem3a_dir / cfg.SEM3A_FEATURES)
    promptstars = pd.read_csv(sem3c_dir / cfg.PROMPTSTAR_CANDIDATES)
    member_residuals = pd.read_csv(sem3c_dir / cfg.MEMBER_RESIDUALS)

    return dataset, features, promptstars, member_residuals


def get_feature_cols_for_nearest(df: pd.DataFrame, block: str):
    return get_feature_cols(df, block)


def find_nearest_exemplars(features: pd.DataFrame, member_residuals: pd.DataFrame, cfg: CFG):
    """
    Prefer SEM-3C.0b residual output if available:
        residual_cos_to_center
    For each family and block, choose max residual_cos_to_center / min residual_l2.
    Main block defaults to center_pca.

    Returns one row per family for nearest exemplar.
    """
    mr = member_residuals.copy()
    if "block" in mr.columns:
        mr = mr[mr["block"] == cfg.MAIN_BLOCK]
    if len(mr) == 0:
        raise ValueError("No member residuals for main block.")

    rows = []
    for fam, g in mr.groupby("seed_family"):
        if "residual_cos_to_center" in g.columns:
            best = g.sort_values("residual_cos_to_center", ascending=False).iloc[0]
        else:
            best = g.sort_values("residual_l2", ascending=True).iloc[0]
        rows.append({
            "seed_family": fam,
            "source_row_id": int(best["row_id"]),
            "nearest_exemplar_prompt": best["prompt"],
            "nearest_exemplar_surface_id": int(best.get("surface_id", -999)),
            "nearest_exemplar_cos_to_center": float(best.get("residual_cos_to_center", np.nan)),
            "nearest_exemplar_l2_to_center": float(best.get("residual_l2", np.nan)),
        })
    return pd.DataFrame(rows)


def build_candidate_dataset(dataset: pd.DataFrame, promptstars: pd.DataFrame, nearest: pd.DataFrame):
    """
    Candidate types:
      - promptstar_natural/structured/compressed from 3C0b
      - nearest_exemplar
      - nearest_plus_structure
      - canonical_minimal_seed
    """
    rows = []
    row_id = 0

    # Prompt* from 3C0b.
    for _, r in promptstars.iterrows():
        rows.append({
            "row_id": row_id,
            "row_type": "candidate",
            "candidate_type": f"promptstar_{r['template_type']}",
            "source_template_type": r["template_type"],
            "seed_family": r["seed_family"],
            "concept_star": r.get("concept_star", ""),
            "operator_id": r.get("operator_id", ""),
            "common_structure": r.get("common_structure", ""),
            "source_row_id": -1,
            "prompt": r["prompt_star_candidate"],
        })
        row_id += 1

    # Nearest exemplar and nearest+structure.
    for _, r in nearest.iterrows():
        fam = r["seed_family"]
        ps_rows = promptstars[promptstars["seed_family"] == fam]
        # Use first natural row to get concept/operator/common.
        ps0 = ps_rows.iloc[0] if len(ps_rows) else {}
        common = ps0.get("common_structure", "")
        concept = ps0.get("concept_star", fam)
        operator = ps0.get("operator_id", "")
        nearest_prompt = r["nearest_exemplar_prompt"]

        rows.append({
            "row_id": row_id,
            "row_type": "candidate",
            "candidate_type": "nearest_exemplar",
            "source_template_type": "nearest_exemplar",
            "seed_family": fam,
            "concept_star": concept,
            "operator_id": operator,
            "common_structure": common,
            "source_row_id": int(r["source_row_id"]),
            "prompt": nearest_prompt,
        })
        row_id += 1

        distilled = (
            f"{nearest_prompt}\n\n"
            f"Preserve the shared structure: {common}.\n"
            f"Use operator: {operator}."
        )
        rows.append({
            "row_id": row_id,
            "row_type": "candidate",
            "candidate_type": "nearest_plus_structure",
            "source_template_type": "nearest_plus_structure",
            "seed_family": fam,
            "concept_star": concept,
            "operator_id": operator,
            "common_structure": common,
            "source_row_id": int(r["source_row_id"]),
            "prompt": distilled,
        })
        row_id += 1

    # Canonical minimal seed from SEM-3A.
    canon = dataset[dataset["row_type"] == "canonical_minimal_seed"]
    for _, r in canon.iterrows():
        rows.append({
            "row_id": row_id,
            "row_type": "candidate",
            "candidate_type": "canonical_minimal_seed",
            "source_template_type": "canonical_minimal_seed",
            "seed_family": r["seed_family"],
            "concept_star": r.get("concept_star", ""),
            "operator_id": r.get("operator_star", ""),
            "common_structure": "",
            "source_row_id": int(r["row_id"]),
            "prompt": r["prompt"],
        })
        row_id += 1

    return pd.DataFrame(rows)


# ============================================================
# PAIRWISE COMPARISON
# ============================================================

def compare_candidates(original_features: pd.DataFrame, candidate_features: pd.DataFrame, block: str):
    Xo, Xc, cols = align_spaces(original_features, candidate_features, block)
    if Xo is None:
        return pd.DataFrame()

    orig = original_features.reset_index(drop=True)
    cand = candidate_features.reset_index(drop=True)

    cand_by_type_family = {}
    for i, row in cand.iterrows():
        cand_by_type_family[(row["candidate_type"], row["seed_family"])] = i

    all_indices = list(range(len(cand)))

    rows = []
    for oi, row in orig.iterrows():
        if row.get("row_type") != "original_prompt":
            continue
        true_family = row["seed_family"]
        x = Xo[oi]

        for candidate_type in sorted(cand["candidate_type"].unique()):
            key = (candidate_type, true_family)
            if key not in cand_by_type_family:
                continue

            same_idx = cand_by_type_family[key]
            xsame = Xc[same_idx]
            same_cos = cosine_np(x, xsame)
            same_l2 = float(np.linalg.norm(x - xsame))

            # Random family candidates of same type.
            rand_idxs = [
                i for i, cr in cand.iterrows()
                if cr["candidate_type"] == candidate_type and cr["seed_family"] != true_family
            ]
            if rand_idxs:
                rand_cos = np.array([cosine_np(x, Xc[i]) for i in rand_idxs])
                rand_l2 = np.array([np.linalg.norm(x - Xc[i]) for i in rand_idxs])
                rand_mean_cos = float(np.mean(rand_cos))
                rand_max_cos = float(np.max(rand_cos))
                rand_mean_l2 = float(np.mean(rand_l2))
                rand_min_l2 = float(np.min(rand_l2))
            else:
                rand_mean_cos = rand_max_cos = rand_mean_l2 = rand_min_l2 = np.nan

            # Nearest candidate among this type.
            type_idxs = [i for i, cr in cand.iterrows() if cr["candidate_type"] == candidate_type]
            type_cos = np.array([cosine_np(x, Xc[i]) for i in type_idxs])
            nn_local_idx = int(np.argmax(type_cos))
            nn_idx = type_idxs[nn_local_idx]
            nn_family = cand.iloc[nn_idx]["seed_family"]

            rows.append({
                "row_id": int(row["row_id"]),
                "block": block,
                "candidate_type": candidate_type,
                "true_family": true_family,
                "original_prompt": row["prompt"],
                "candidate_prompt": cand.iloc[same_idx]["prompt"],
                "candidate_source_row_id": int(cand.iloc[same_idx].get("source_row_id", -1)),
                "same_family_cos": same_cos,
                "same_family_l2": same_l2,
                "random_family_mean_cos": rand_mean_cos,
                "random_family_max_cos": rand_max_cos,
                "random_family_mean_l2": rand_mean_l2,
                "random_family_min_l2": rand_min_l2,
                "cos_margin_vs_random_mean": same_cos - rand_mean_cos if np.isfinite(rand_mean_cos) else np.nan,
                "cos_margin_vs_random_max": same_cos - rand_max_cos if np.isfinite(rand_max_cos) else np.nan,
                "l2_gain_vs_random_mean": rand_mean_l2 - same_l2 if np.isfinite(rand_mean_l2) else np.nan,
                "l2_gain_vs_random_min": rand_min_l2 - same_l2 if np.isfinite(rand_min_l2) else np.nan,
                "nearest_same_type_family": nn_family,
                "nearest_same_type_correct_family": int(nn_family == true_family),
                "n_features": len(cols),
            })

    return pd.DataFrame(rows)


def summarize_pairwise(pair_df: pd.DataFrame):
    rows = []
    for (block, ctype), g in pair_df.groupby(["block", "candidate_type"]):
        rows.append({
            "block": block,
            "candidate_type": ctype,
            "n": int(len(g)),
            "mean_same_family_cos": float(g["same_family_cos"].mean()),
            "mean_random_family_mean_cos": float(g["random_family_mean_cos"].mean()),
            "mean_cos_margin_vs_random_mean": float(g["cos_margin_vs_random_mean"].mean()),
            "frac_cos_gt_random_mean": float((g["cos_margin_vs_random_mean"] > 0).mean()),
            "frac_cos_gt_random_max": float((g["cos_margin_vs_random_max"] > 0).mean()),
            "mean_same_family_l2": float(g["same_family_l2"].mean()),
            "mean_l2_gain_vs_random_mean": float(g["l2_gain_vs_random_mean"].mean()),
            "frac_l2_better_than_random_mean": float((g["l2_gain_vs_random_mean"] > 0).mean()),
            "nearest_same_type_correct_family_rate": float(g["nearest_same_type_correct_family"].mean()),
        })
    return pd.DataFrame(rows)


def family_summary(pair_df: pd.DataFrame):
    rows = []
    for (block, ctype, fam), g in pair_df.groupby(["block", "candidate_type", "true_family"]):
        rows.append({
            "block": block,
            "candidate_type": ctype,
            "seed_family": fam,
            "n": int(len(g)),
            "mean_cos_margin_vs_random_mean": float(g["cos_margin_vs_random_mean"].mean()),
            "frac_cos_gt_random_mean": float((g["cos_margin_vs_random_mean"] > 0).mean()),
            "mean_l2_gain_vs_random_mean": float(g["l2_gain_vs_random_mean"].mean()),
            "nearest_same_type_correct_family_rate": float(g["nearest_same_type_correct_family"].mean()),
        })
    return pd.DataFrame(rows)


def stats_tests(pair_df: pd.DataFrame):
    rows = []
    for (block, ctype), g in pair_df.groupby(["block", "candidate_type"]):
        cos_same = g["same_family_cos"].values
        cos_rand = g["random_family_mean_cos"].values
        l2_same = g["same_family_l2"].values
        l2_rand = g["random_family_mean_l2"].values

        try:
            tt = ttest_rel(cos_same, cos_rand, nan_policy="omit")
            t_stat, t_p = float(tt.statistic), float(tt.pvalue)
        except Exception:
            t_stat, t_p = np.nan, np.nan
        try:
            ww = wilcoxon(cos_same - cos_rand)
            w_stat, w_p = float(ww.statistic), float(ww.pvalue)
        except Exception:
            w_stat, w_p = np.nan, np.nan

        try:
            tt2 = ttest_rel(l2_rand, l2_same, nan_policy="omit")
            t2_stat, t2_p = float(tt2.statistic), float(tt2.pvalue)
        except Exception:
            t2_stat, t2_p = np.nan, np.nan

        rows.append({
            "block": block,
            "candidate_type": ctype,
            "n": int(len(g)),
            "cos_margin_mean": float(np.nanmean(cos_same - cos_rand)),
            "cos_paired_t_stat": t_stat,
            "cos_paired_t_p": t_p,
            "cos_wilcoxon_stat": w_stat,
            "cos_wilcoxon_p": w_p,
            "l2_gain_mean": float(np.nanmean(l2_rand - l2_same)),
            "l2_paired_t_stat": t2_stat,
            "l2_paired_t_p": t2_p,
        })

    return pd.DataFrame(rows)


def build_summary(strategy_df: pd.DataFrame):
    summary = {
        "config": asdict(cfg),
        "verdict": "UNDETERMINED",
        "main_block": cfg.MAIN_BLOCK,
        "best_overall": {},
        "best_main_block": {},
        "diagnosis": "",
        "interpretation": [],
    }

    if len(strategy_df):
        df = strategy_df.copy()
        df["score"] = (
            df["mean_cos_margin_vs_random_mean"].fillna(-999)
            + df["frac_cos_gt_random_mean"].fillna(0)
            + df["nearest_same_type_correct_family_rate"].fillna(0)
            + 0.1 * df["mean_l2_gain_vs_random_mean"].fillna(0)
        )
        best = df.sort_values("score", ascending=False).iloc[0].to_dict()
        summary["best_overall"] = best

        main = df[df["block"] == cfg.MAIN_BLOCK]
        if len(main):
            main_best = main.sort_values("score", ascending=False).iloc[0].to_dict()
            summary["best_main_block"] = main_best
        else:
            main_best = best

        # Check diagnostic comparisons.
        def get(block, ctype, field):
            sub = df[(df["block"] == block) & (df["candidate_type"] == ctype)]
            if len(sub):
                return float(sub.iloc[0].get(field, np.nan))
            return np.nan

        main_block = cfg.MAIN_BLOCK
        nearest_margin = get(main_block, "nearest_exemplar", "mean_cos_margin_vs_random_mean")
        natural_margin = get(main_block, "promptstar_natural_prompt_star", "mean_cos_margin_vs_random_mean")
        distilled_margin = get(main_block, "nearest_plus_structure", "mean_cos_margin_vs_random_mean")
        canonical_margin = get(main_block, "canonical_minimal_seed", "mean_cos_margin_vs_random_mean")

        if np.isfinite(nearest_margin) and nearest_margin > natural_margin and nearest_margin > canonical_margin:
            summary["diagnosis"] = "LANGUAGE_TEMPLATE_BOTTLENECK_NEAREST_EXEMPLAR_BETTER"
        elif np.isfinite(distilled_margin) and distilled_margin > nearest_margin and distilled_margin > natural_margin:
            summary["diagnosis"] = "EXEMPLAR_PLUS_STRUCTURE_BEST"
        elif np.isfinite(canonical_margin) and canonical_margin >= max(natural_margin, nearest_margin, distilled_margin):
            summary["diagnosis"] = "CANONICAL_REMAINS_BEST"
        else:
            summary["diagnosis"] = "NO_CLEAR_ENCODING_WINNER"

        mb = summary.get("best_main_block", {})
        margin = mb.get("mean_cos_margin_vs_random_mean", -999)
        frac = mb.get("frac_cos_gt_random_mean", 0)
        nn = mb.get("nearest_same_type_correct_family_rate", 0)
        l2_gain = mb.get("mean_l2_gain_vs_random_mean", -999)

        if margin > 0 and frac >= 0.85 and nn >= 0.70 and l2_gain > 0:
            summary["verdict"] = "PASS_STRONG_PROMPT_ENCODING"
        elif margin > 0 and frac >= 0.70 and nn >= 0.50:
            summary["verdict"] = "PASS_LITE_PROMPT_ENCODING"
        elif margin > 0 and frac >= 0.60:
            summary["verdict"] = "PARTIAL_PASS_PROMPT_ENCODING_SIGNAL"
        else:
            summary["verdict"] = "NO_PASS_YET"

    summary["interpretation"] = [
        "If nearest_exemplar beats generated Prompt*, the family center is real but current language template is weak.",
        "If nearest_plus_structure beats nearest_exemplar, adding distilled common structure helps encode μ_F.",
        "If all candidates fail, μ_F may be a statistical center not realizable by a single prompt, or feature spaces are misaligned.",
        "If Prompt* candidates pass, SEM-3B regeneration can proceed with that encoding strategy.",
    ]
    return summary


# ============================================================
# MAIN
# ============================================================

def main():
    set_seed(cfg.RANDOM_SEED)
    outdir = Path(cfg.OUTPUT_DIR)
    ensure_dir(str(outdir))
    json_dump(asdict(cfg), outdir / "sem3b1_config.json")

    dataset, features, promptstars, member_residuals = load_inputs(cfg)
    nearest = find_nearest_exemplars(features, member_residuals, cfg)
    nearest.to_csv(outdir / "sem3b1_nearest_exemplars.csv", index=False, encoding="utf-8-sig")

    candidate_dataset = build_candidate_dataset(dataset, promptstars, nearest)
    candidate_dataset.to_csv(outdir / "sem3b1_candidate_dataset.csv", index=False, encoding="utf-8-sig")

    feat_path = outdir / "sem3b1_candidate_features.csv"
    if cfg.REUSE_CANDIDATE_FEATURES_IF_EXISTS and feat_path.exists():
        print(f"[SEM-3B.1] Reusing candidate features: {feat_path}")
        candidate_features = pd.read_csv(feat_path)
    else:
        model, tokenizer = load_model_and_tokenizer(cfg)
        candidate_features = extract_all_features(candidate_dataset, model, tokenizer, cfg)
        candidate_features.to_csv(feat_path, index=False, encoding="utf-8-sig")

    original_features = features[features["row_type"] == "original_prompt"].copy()

    blocks = ["center_pca", "decision", "mid", "all", "scalar", "transport", "init"]
    pair_rows = []
    for block in blocks:
        print(f"[SEM-3B.1] Comparing block={block}")
        out = compare_candidates(original_features, candidate_features, block)
        if len(out):
            pair_rows.append(out)

    pair_df = pd.concat(pair_rows, ignore_index=True) if pair_rows else pd.DataFrame()
    pair_df.to_csv(outdir / "sem3b1_pairwise_regeneration.csv", index=False, encoding="utf-8-sig")

    strat_df = summarize_pairwise(pair_df) if len(pair_df) else pd.DataFrame()
    strat_df.to_csv(outdir / "sem3b1_strategy_summary.csv", index=False, encoding="utf-8-sig")

    fam_df = family_summary(pair_df) if len(pair_df) else pd.DataFrame()
    fam_df.to_csv(outdir / "sem3b1_family_summary.csv", index=False, encoding="utf-8-sig")

    stats_df = stats_tests(pair_df) if len(pair_df) else pd.DataFrame()
    stats_df.to_csv(outdir / "sem3b1_statistical_tests.csv", index=False, encoding="utf-8-sig")

    summary = build_summary(strat_df)
    json_dump(summary, outdir / "sem3b1_results_summary.json")

    print("=" * 100)
    print("SEM-3B.1: Prompt* Encoding Ablation")
    print("=" * 100)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print("\nOutput files:")
    for p in [
        "sem3b1_config.json",
        "sem3b1_nearest_exemplars.csv",
        "sem3b1_candidate_dataset.csv",
        "sem3b1_candidate_features.csv",
        "sem3b1_pairwise_regeneration.csv",
        "sem3b1_strategy_summary.csv",
        "sem3b1_family_summary.csv",
        "sem3b1_statistical_tests.csv",
        "sem3b1_results_summary.json",
    ]:
        print("  -", outdir / p)


if __name__ == "__main__":
    main()
