# -*- coding: utf-8 -*-
"""
GPT_204_SEM_3B_promptstar_regeneration_audit.py

SEM-3B: Prompt*(mu_F) Regeneration Audit
----------------------------------------

Goal:
    Test whether Prompt* generated from SeedFamily maximal common structure
    can regenerate trajectories closer to original prompts than:
        1. hand-written canonical minimal seed
        2. random-family Prompt*
        3. compressed seed variant, etc.

Theory:
    True Prompt is not uniquely invertible.
    SeedFamily center μ_F captures maximal common structure.
    Prompt* should be generated from μ_F + structural prior.

Pipeline:
    SEM-3A:
        original prompt trajectories + canonical minimal seed trajectories

    SEM-3C.0b:
        family center μ_F
        prompt_star_candidates.csv

    SEM-3B:
        forward Prompt* candidates
        compare T(original) with:
            T(prompt_star_same_family)
            T(canonical_same_family)
            T(prompt_star_random_family)
        over feature blocks:
            center_pca, scalar, transport, init, mid, decision, all

Outputs:
    sem3b_outputs/
      sem3b_config.json
      sem3b_promptstar_dataset.csv
      sem3b_promptstar_features.csv
      sem3b_pairwise_regeneration.csv
      sem3b_family_summary.csv
      sem3b_template_type_summary.csv
      sem3b_results_summary.json

Run:
    python GPT_204_SEM_3B_promptstar_regeneration_audit.py

Notes:
    - This script reuses the same feature extractor as SEM-3A.
    - It expects sem3a_outputs and sem3c0b_outputs to exist.
    - It forwards only Prompt* candidates, not all original prompts again, if sem3a_features.csv exists.
"""

import json
import random
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import List, Tuple, Dict, Any

import numpy as np
import pandas as pd

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from scipy.stats import ttest_rel, wilcoxon


# ============================================================
# CONFIG
# ============================================================

@dataclass
class CFG:
    MODEL_PATH: str = r"D:\model\models--Qwen--Qwen2.5-1.5B-Instruct\main"

    SEM3A_DIR: str = "./sem3a_outputs"
    SEM3C0B_DIR: str = "./sem3c0b_outputs"
    OUTPUT_DIR: str = "./sem3b_outputs"

    SEM3A_DATASET: str = "sem3a_dataset.csv"
    SEM3A_FEATURES: str = "sem3a_features.csv"
    PROMPTSTAR_CANDIDATES: str = "sem3c0b_prompt_star_candidates.csv"

    TOPK_LIST: Tuple[int, ...] = (100, 500)
    LAYERS: Tuple[int, ...] = tuple(range(0, 26))
    BATCH_SIZE: int = 4
    MAX_LENGTH: int = 192
    CENTER_PCA_DIM: int = 16
    DEVICE: str = "cuda" if torch.cuda.is_available() else "cpu"
    DTYPE: str = "auto"
    RANDOM_SEED: int = 42

    REUSE_PROMPTSTAR_FEATURES_IF_EXISTS: bool = True

    # Main block to judge. SEM-3A and 3C.0b identified center_pca as strongest.
    MAIN_BLOCK: str = "center_pca"

    # Compare all three Prompt* types generated by 3C.0b.
    TEMPLATE_TYPES: Tuple[str, ...] = (
        "natural_prompt_star",
        "structured_prompt_star",
        "compressed_prompt_star",
    )


cfg = CFG()


# ============================================================
# UTILITIES
# ============================================================

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def ensure_dir(path: str):
    Path(path).mkdir(parents=True, exist_ok=True)


def json_dump(obj: Any, path: Path):
    def convert(o):
        if isinstance(o, (np.integer,)):
            return int(o)
        if isinstance(o, (np.floating,)):
            return float(o)
        if isinstance(o, np.ndarray):
            return o.tolist()
        if isinstance(o, Path):
            return str(o)
        if isinstance(o, float) and np.isnan(o):
            return None
        return str(o)

    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2, default=convert)


def get_torch_dtype(dtype_name: str):
    if dtype_name == "float16":
        return torch.float16
    if dtype_name == "bfloat16":
        return torch.bfloat16
    if dtype_name == "float32":
        return torch.float32
    return "auto"


def cosine_np(a, b, eps=1e-9):
    a = np.asarray(a)
    b = np.asarray(b)
    na = np.linalg.norm(a)
    nb = np.linalg.norm(b)
    if na < eps or nb < eps:
        return 0.0
    return float(np.dot(a, b) / (na * nb))


def jaccard(a: set, b: set):
    if not a and not b:
        return 1.0
    u = len(a | b)
    return len(a & b) / u if u else 0.0


# ============================================================
# MODEL
# ============================================================

def load_model_and_tokenizer(cfg: CFG):
    print(f"[SEM-3B] Loading model: {cfg.MODEL_PATH}")
    dtype = get_torch_dtype(cfg.DTYPE)

    tokenizer = AutoTokenizer.from_pretrained(
        cfg.MODEL_PATH,
        trust_remote_code=True,
        local_files_only=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        cfg.MODEL_PATH,
        trust_remote_code=True,
        local_files_only=True,
        torch_dtype=dtype,
        device_map="auto" if cfg.DEVICE == "cuda" else None,
    )
    if cfg.DEVICE != "cuda":
        model.to(cfg.DEVICE)
    model.eval()
    return model, tokenizer


def get_lm_head_weight(model):
    if hasattr(model, "get_output_embeddings") and model.get_output_embeddings() is not None:
        return model.get_output_embeddings().weight
    raise RuntimeError("Cannot find output embedding / lm_head weight.")


# ============================================================
# FEATURE EXTRACTION
# ============================================================

@torch.no_grad()
def extract_batch(prompts: List[str], model, tokenizer, cfg: CFG):
    enc = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=cfg.MAX_LENGTH,
    )
    enc = {k: v.to(model.device) for k, v in enc.items()}

    out = model(
        **enc,
        output_hidden_states=True,
        use_cache=False,
        return_dict=True,
    )

    hidden_states = out.hidden_states
    W = get_lm_head_weight(model).to(model.device)
    last_pos = enc["attention_mask"].sum(dim=1) - 1

    scalar_rows = []
    center_records = []

    for bi in range(len(prompts)):
        row = {}
        prev_center = {}
        prev_set = {}

        for layer in cfg.LAYERS:
            hs_index = layer + 1
            if hs_index >= len(hidden_states):
                continue

            h = hidden_states[hs_index][bi, last_pos[bi], :]
            logits = torch.matmul(h, W.T)

            for k in cfg.TOPK_LIST:
                vals, ids = torch.topk(logits, k=k, dim=-1)
                vals_np = vals.detach().float().cpu().numpy()
                ids_np = ids.detach().cpu().numpy().astype(np.int64)

                emb = W[ids].detach().float()
                center = emb.mean(dim=0)
                center_np = center.cpu().numpy()

                emb_norm = torch.nn.functional.normalize(emb, dim=-1)
                c_norm = torch.nn.functional.normalize(center.unsqueeze(0), dim=-1)
                cos = (emb_norm * c_norm).sum(dim=-1)
                spread = float((1.0 - cos).mean().detach().cpu())

                probs = torch.softmax(vals.float(), dim=-1)
                entropy = float((-(probs * torch.log(probs + 1e-12)).sum()).detach().cpu())

                id_set = set(ids_np.tolist())
                p = f"k{k}_L{layer}"

                row[f"{p}_spread"] = spread
                row[f"{p}_entropy"] = entropy
                row[f"{p}_gap"] = float(vals_np[0] - vals_np[-1])
                row[f"{p}_meanlogit"] = float(vals_np.mean())
                row[f"{p}_center_norm"] = float(np.linalg.norm(center_np))

                if k in prev_center:
                    row[f"{p}_center_shift_cosdist"] = 1.0 - cosine_np(prev_center[k], center_np)
                    row[f"{p}_center_shift_l2"] = float(np.linalg.norm(center_np - prev_center[k]))
                else:
                    row[f"{p}_center_shift_cosdist"] = 0.0
                    row[f"{p}_center_shift_l2"] = 0.0

                if k in prev_set:
                    jac = jaccard(prev_set[k], id_set)
                    row[f"{p}_jaccard_prev"] = jac
                    row[f"{p}_jaccard_dist_prev"] = 1.0 - jac
                else:
                    row[f"{p}_jaccard_prev"] = 1.0
                    row[f"{p}_jaccard_dist_prev"] = 0.0

                prev_center[k] = center_np
                prev_set[k] = id_set

                center_records.append({
                    "batch_index": bi,
                    "layer": layer,
                    "k": k,
                    "center": center_np,
                })

        scalar_rows.append(row)

    return scalar_rows, center_records


def extract_all_features(df: pd.DataFrame, model, tokenizer, cfg: CFG):
    prompts = df["prompt"].astype(str).tolist()
    all_scalar = []
    all_center_records = []

    for start in range(0, len(prompts), cfg.BATCH_SIZE):
        end = min(start + cfg.BATCH_SIZE, len(prompts))
        print(f"[SEM-3B] Extracting {start}:{end}/{len(prompts)}")
        scalar_rows, center_records = extract_batch(prompts[start:end], model, tokenizer, cfg)

        for i, r in enumerate(scalar_rows):
            r["row_id"] = int(df.iloc[start + i]["row_id"])
            all_scalar.append(r)

        for rec in center_records:
            rec["row_id"] = int(df.iloc[start + rec["batch_index"]]["row_id"])
            del rec["batch_index"]
            all_center_records.append(rec)

    scalar_df = pd.DataFrame(all_scalar)

    # Center PCA across Prompt* rows.
    center_feature_rows = {int(rid): {"row_id": int(rid)} for rid in df["row_id"].values}
    for k in cfg.TOPK_LIST:
        for layer in cfg.LAYERS:
            recs = [r for r in all_center_records if r["k"] == k and r["layer"] == layer]
            if not recs:
                continue
            X = np.vstack([r["center"] for r in recs])
            n_comp = min(cfg.CENTER_PCA_DIM, X.shape[0], X.shape[1])
            pca = PCA(n_components=n_comp, random_state=cfg.RANDOM_SEED)
            Z = pca.fit_transform(StandardScaler().fit_transform(X))
            for rec, z in zip(recs, Z):
                rid = int(rec["row_id"])
                for j in range(n_comp):
                    center_feature_rows[rid][f"k{k}_L{layer}_centerPC{j+1}"] = float(z[j])

    center_df = pd.DataFrame(list(center_feature_rows.values())).fillna(0.0)
    feature_df = df.merge(scalar_df, on="row_id", how="left").merge(center_df, on="row_id", how="left")
    return feature_df


# ============================================================
# LOAD INPUTS / DATASET
# ============================================================

def build_promptstar_dataset(prompt_candidates: pd.DataFrame, cfg: CFG):
    rows = []
    for _, r in prompt_candidates.iterrows():
        if r["template_type"] not in cfg.TEMPLATE_TYPES:
            continue
        rows.append({
            "row_id": len(rows),
            "row_type": "prompt_star",
            "seed_family": r["seed_family"],
            "template_type": r["template_type"],
            "concept_star": r.get("concept_star", ""),
            "operator_id": r.get("operator_id", ""),
            "common_structure": r.get("common_structure", ""),
            "prompt": r["prompt_star_candidate"],
        })
    return pd.DataFrame(rows)


def load_inputs(cfg: CFG):
    sem3a_dir = Path(cfg.SEM3A_DIR)
    sem3c_dir = Path(cfg.SEM3C0B_DIR)

    sem3a_dataset = pd.read_csv(sem3a_dir / cfg.SEM3A_DATASET)
    sem3a_features = pd.read_csv(sem3a_dir / cfg.SEM3A_FEATURES)
    prompt_candidates = pd.read_csv(sem3c_dir / cfg.PROMPTSTAR_CANDIDATES)

    promptstar_dataset = build_promptstar_dataset(prompt_candidates, cfg)

    return sem3a_dataset, sem3a_features, prompt_candidates, promptstar_dataset


# ============================================================
# FEATURE BLOCKS
# ============================================================

def get_feature_cols(df: pd.DataFrame, block: str):
    exclude = {
        "row_id", "row_type", "seed_family", "concept_star", "operator_star",
        "surface_id", "prompt", "template_type", "operator_id", "common_structure"
    }
    numeric = [c for c in df.columns if c not in exclude and pd.api.types.is_numeric_dtype(df[c])]

    if block == "all":
        return numeric
    if block == "scalar":
        return [c for c in numeric if "centerPC" not in c]
    if block == "center_pca":
        return [c for c in numeric if "centerPC" in c]
    if block == "transport":
        return [c for c in numeric if any(k in c for k in ["shift", "jaccard"])]
    if block == "init":
        return [c for c in numeric if any(f"_L{i}_" in c for i in range(0, 7))]
    if block == "mid":
        return [c for c in numeric if any(f"_L{i}_" in c for i in range(7, 20))]
    if block == "decision":
        return [c for c in numeric if any(f"_L{i}_" in c for i in range(20, 26))]
    raise ValueError(block)


def make_X(df: pd.DataFrame, cols):
    return df[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0).astype(np.float32).values


# ============================================================
# COMPARISON
# ============================================================

def align_feature_spaces(original_features: pd.DataFrame, promptstar_features: pd.DataFrame, block: str):
    cols_orig = set(get_feature_cols(original_features, block))
    cols_ps = set(get_feature_cols(promptstar_features, block))
    cols = sorted(cols_orig & cols_ps)
    if not cols:
        return None, None, []

    combined = pd.concat(
        [
            original_features[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0),
            promptstar_features[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0),
        ],
        axis=0,
    )
    scaler = StandardScaler()
    scaler.fit(combined.values.astype(np.float32))

    Xo = scaler.transform(original_features[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0).values.astype(np.float32))
    Xp = scaler.transform(promptstar_features[cols].replace([np.inf, -np.inf], np.nan).fillna(0.0).values.astype(np.float32))
    return Xo, Xp, cols


def compare_regeneration(original_features: pd.DataFrame, promptstar_features: pd.DataFrame, block: str):
    Xo, Xp, cols = align_feature_spaces(original_features, promptstar_features, block)
    if Xo is None:
        return pd.DataFrame()

    orig = original_features.reset_index(drop=True)
    ps = promptstar_features.reset_index(drop=True)

    # Candidate maps.
    ps_by_family_type = {}
    for i, row in ps.iterrows():
        ps_by_family_type[(row["seed_family"], row["template_type"])] = i

    ps_indices_by_family = {}
    for i, row in ps.iterrows():
        ps_indices_by_family.setdefault(row["seed_family"], []).append(i)

    all_ps_indices = list(range(len(ps)))

    rows = []
    for oi, row in orig.iterrows():
        if row.get("row_type") != "original_prompt":
            continue
        true_family = row["seed_family"]
        x = Xo[oi]

        for template_type in cfg.TEMPLATE_TYPES:
            key = (true_family, template_type)
            if key not in ps_by_family_type:
                continue

            same_idx = ps_by_family_type[key]
            xsame = Xp[same_idx]

            # Same-family promptstar similarity.
            same_cos = cosine_np(x, xsame)
            same_l2 = float(np.linalg.norm(x - xsame))

            # Random-family baseline: all promptstars with same template_type but different family.
            rand_idxs = [
                i for i, pr in ps.iterrows()
                if pr["template_type"] == template_type and pr["seed_family"] != true_family
            ]
            if rand_idxs:
                rand_cos = np.array([cosine_np(x, Xp[i]) for i in rand_idxs])
                rand_l2 = np.array([np.linalg.norm(x - Xp[i]) for i in rand_idxs])
                rand_mean_cos = float(np.mean(rand_cos))
                rand_max_cos = float(np.max(rand_cos))
                rand_mean_l2 = float(np.mean(rand_l2))
                rand_min_l2 = float(np.min(rand_l2))
            else:
                rand_mean_cos = rand_max_cos = rand_mean_l2 = rand_min_l2 = np.nan

            # Nearest Prompt* among all candidates.
            all_cos = np.array([cosine_np(x, Xp[i]) for i in all_ps_indices])
            nn_idx = int(np.argmax(all_cos))
            nn_family = ps.iloc[nn_idx]["seed_family"]
            nn_template_type = ps.iloc[nn_idx]["template_type"]

            rows.append({
                "row_id": int(row["row_id"]),
                "block": block,
                "template_type": template_type,
                "true_family": true_family,
                "original_prompt": row["prompt"],
                "promptstar_prompt": ps.iloc[same_idx]["prompt"],
                "same_family_cos": same_cos,
                "same_family_l2": same_l2,
                "random_family_mean_cos": rand_mean_cos,
                "random_family_max_cos": rand_max_cos,
                "random_family_mean_l2": rand_mean_l2,
                "random_family_min_l2": rand_min_l2,
                "cos_margin_vs_random_mean": same_cos - rand_mean_cos if np.isfinite(rand_mean_cos) else np.nan,
                "cos_margin_vs_random_max": same_cos - rand_max_cos if np.isfinite(rand_max_cos) else np.nan,
                "l2_gain_vs_random_mean": rand_mean_l2 - same_l2 if np.isfinite(rand_mean_l2) else np.nan,
                "l2_gain_vs_random_min": rand_min_l2 - same_l2 if np.isfinite(rand_min_l2) else np.nan,
                "nearest_promptstar_family": nn_family,
                "nearest_promptstar_template_type": nn_template_type,
                "nearest_promptstar_correct_family": int(nn_family == true_family),
                "n_features": len(cols),
            })

    return pd.DataFrame(rows)


def summarize_pairwise(pair_df: pd.DataFrame):
    rows = []
    for (block, template_type), g in pair_df.groupby(["block", "template_type"]):
        rows.append({
            "block": block,
            "template_type": template_type,
            "n": int(len(g)),
            "mean_same_family_cos": float(g["same_family_cos"].mean()),
            "mean_random_family_mean_cos": float(g["random_family_mean_cos"].mean()),
            "mean_cos_margin_vs_random_mean": float(g["cos_margin_vs_random_mean"].mean()),
            "frac_cos_gt_random_mean": float((g["cos_margin_vs_random_mean"] > 0).mean()),
            "frac_cos_gt_random_max": float((g["cos_margin_vs_random_max"] > 0).mean()),
            "mean_same_family_l2": float(g["same_family_l2"].mean()),
            "mean_l2_gain_vs_random_mean": float(g["l2_gain_vs_random_mean"].mean()),
            "frac_l2_better_than_random_mean": float((g["l2_gain_vs_random_mean"] > 0).mean()),
            "nearest_promptstar_correct_family_rate": float(g["nearest_promptstar_correct_family"].mean()),
        })
    return pd.DataFrame(rows)


def family_summary(pair_df: pd.DataFrame):
    rows = []
    for (block, template_type, fam), g in pair_df.groupby(["block", "template_type", "true_family"]):
        rows.append({
            "block": block,
            "template_type": template_type,
            "seed_family": fam,
            "n": int(len(g)),
            "mean_cos_margin_vs_random_mean": float(g["cos_margin_vs_random_mean"].mean()),
            "frac_cos_gt_random_mean": float((g["cos_margin_vs_random_mean"] > 0).mean()),
            "frac_cos_gt_random_max": float((g["cos_margin_vs_random_max"] > 0).mean()),
            "mean_l2_gain_vs_random_mean": float(g["l2_gain_vs_random_mean"].mean()),
            "nearest_promptstar_correct_family_rate": float(g["nearest_promptstar_correct_family"].mean()),
        })
    return pd.DataFrame(rows)


def statistical_tests(pair_df: pd.DataFrame):
    rows = []
    for (block, template_type), g in pair_df.groupby(["block", "template_type"]):
        cos_same = g["same_family_cos"].values
        cos_rand = g["random_family_mean_cos"].values
        l2_same = g["same_family_l2"].values
        l2_rand = g["random_family_mean_l2"].values

        # paired t and Wilcoxon for cos margin and l2 gain.
        try:
            t_cos = ttest_rel(cos_same, cos_rand, nan_policy="omit")
            t_cos_stat, t_cos_p = float(t_cos.statistic), float(t_cos.pvalue)
        except Exception:
            t_cos_stat, t_cos_p = np.nan, np.nan
        try:
            w_cos = wilcoxon(cos_same - cos_rand)
            w_cos_stat, w_cos_p = float(w_cos.statistic), float(w_cos.pvalue)
        except Exception:
            w_cos_stat, w_cos_p = np.nan, np.nan

        try:
            t_l2 = ttest_rel(l2_rand, l2_same, nan_policy="omit")  # rand - same > 0
            t_l2_stat, t_l2_p = float(t_l2.statistic), float(t_l2.pvalue)
        except Exception:
            t_l2_stat, t_l2_p = np.nan, np.nan
        try:
            w_l2 = wilcoxon(l2_rand - l2_same)
            w_l2_stat, w_l2_p = float(w_l2.statistic), float(w_l2.pvalue)
        except Exception:
            w_l2_stat, w_l2_p = np.nan, np.nan

        rows.append({
            "block": block,
            "template_type": template_type,
            "n": int(len(g)),
            "cos_margin_mean": float(np.nanmean(cos_same - cos_rand)),
            "cos_paired_t_stat": t_cos_stat,
            "cos_paired_t_p": t_cos_p,
            "cos_wilcoxon_stat": w_cos_stat,
            "cos_wilcoxon_p": w_cos_p,
            "l2_gain_mean": float(np.nanmean(l2_rand - l2_same)),
            "l2_paired_t_stat": t_l2_stat,
            "l2_paired_t_p": t_l2_p,
            "l2_wilcoxon_stat": w_l2_stat,
            "l2_wilcoxon_p": w_l2_p,
        })
    return pd.DataFrame(rows)


def build_results_summary(pair_summary: pd.DataFrame, stats_df: pd.DataFrame):
    summary = {
        "config": asdict(cfg),
        "verdict": "UNDETERMINED",
        "best": {},
        "main_block": cfg.MAIN_BLOCK,
        "interpretation": [],
    }

    if len(pair_summary):
        # Main score prioritizes same-family cosine margin, fraction gt random, and NN correct.
        ps = pair_summary.copy()
        ps["score"] = (
            ps["mean_cos_margin_vs_random_mean"].fillna(-999)
            + ps["frac_cos_gt_random_mean"].fillna(0)
            + ps["nearest_promptstar_correct_family_rate"].fillna(0)
        )
        best = ps.sort_values("score", ascending=False).iloc[0].to_dict()
        summary["best"] = best

        main_candidates = ps[ps["block"] == cfg.MAIN_BLOCK]
        if len(main_candidates):
            main_best = main_candidates.sort_values("score", ascending=False).iloc[0].to_dict()
            summary["main_block_best"] = main_best

    # Verdict logic.
    best = summary.get("main_block_best", summary.get("best", {}))
    margin = best.get("mean_cos_margin_vs_random_mean", -999)
    frac = best.get("frac_cos_gt_random_mean", 0)
    nn = best.get("nearest_promptstar_correct_family_rate", 0)
    l2_gain = best.get("mean_l2_gain_vs_random_mean", -999)

    if margin > 0 and frac >= 0.85 and nn >= 0.70 and l2_gain > 0:
        summary["verdict"] = "PASS_STRONG_PROMPTSTAR_REGENERATION"
    elif margin > 0 and frac >= 0.70 and nn >= 0.50:
        summary["verdict"] = "PASS_LITE_PROMPTSTAR_REGENERATION"
    elif margin > 0 and frac >= 0.60:
        summary["verdict"] = "PARTIAL_PASS_PROMPTSTAR_SIGNAL"
    else:
        summary["verdict"] = "NO_PASS_YET"

    summary["interpretation"] = [
        "This tests regenerated Prompt* candidates, not exact original prompt inversion.",
        "A positive result means Prompt*(mu_F) trajectories are closer to original prompt trajectories than random-family Prompt*.",
        "template_type comparison identifies whether natural, structured, or compressed Prompt* best represents the family center.",
        "The next step after PASS is to compare Prompt* against hand-written canonical seed directly using the same feature extractor.",
    ]
    return summary


# ============================================================
# MAIN
# ============================================================

def main():
    set_seed(cfg.RANDOM_SEED)
    outdir = Path(cfg.OUTPUT_DIR)
    ensure_dir(str(outdir))
    json_dump(asdict(cfg), outdir / "sem3b_config.json")

    sem3a_dataset, sem3a_features, prompt_candidates, promptstar_dataset = load_inputs(cfg)
    promptstar_dataset.to_csv(outdir / "sem3b_promptstar_dataset.csv", index=False, encoding="utf-8-sig")

    ps_feat_path = outdir / "sem3b_promptstar_features.csv"
    if cfg.REUSE_PROMPTSTAR_FEATURES_IF_EXISTS and ps_feat_path.exists():
        print(f"[SEM-3B] Reusing Prompt* features: {ps_feat_path}")
        promptstar_features = pd.read_csv(ps_feat_path)
    else:
        model, tokenizer = load_model_and_tokenizer(cfg)
        promptstar_features = extract_all_features(promptstar_dataset, model, tokenizer, cfg)
        promptstar_features.to_csv(ps_feat_path, index=False, encoding="utf-8-sig")
        print(f"[SEM-3B] Prompt* features saved: {ps_feat_path}")

    # Compare only original prompt rows from SEM-3A.
    original_features = sem3a_features[sem3a_features["row_type"] == "original_prompt"].copy()

    blocks = ["center_pca", "decision", "mid", "all", "scalar", "transport", "init"]
    pairwise = []
    for block in blocks:
        print(f"[SEM-3B] Comparing block={block}")
        dfb = compare_regeneration(original_features, promptstar_features, block)
        if len(dfb):
            pairwise.append(dfb)

    pair_df = pd.concat(pairwise, ignore_index=True) if pairwise else pd.DataFrame()
    pair_df.to_csv(outdir / "sem3b_pairwise_regeneration.csv", index=False, encoding="utf-8-sig")

    fam_df = family_summary(pair_df) if len(pair_df) else pd.DataFrame()
    fam_df.to_csv(outdir / "sem3b_family_summary.csv", index=False, encoding="utf-8-sig")

    template_df = summarize_pairwise(pair_df) if len(pair_df) else pd.DataFrame()
    template_df.to_csv(outdir / "sem3b_template_type_summary.csv", index=False, encoding="utf-8-sig")

    stats_df = statistical_tests(pair_df) if len(pair_df) else pd.DataFrame()
    stats_df.to_csv(outdir / "sem3b_statistical_tests.csv", index=False, encoding="utf-8-sig")

    summary = build_results_summary(template_df, stats_df)
    json_dump(summary, outdir / "sem3b_results_summary.json")

    print("=" * 100)
    print("SEM-3B: Prompt*(mu_F) Regeneration Audit")
    print("=" * 100)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print("\nOutput files:")
    for p in [
        "sem3b_config.json",
        "sem3b_promptstar_dataset.csv",
        "sem3b_promptstar_features.csv",
        "sem3b_pairwise_regeneration.csv",
        "sem3b_family_summary.csv",
        "sem3b_template_type_summary.csv",
        "sem3b_statistical_tests.csv",
        "sem3b_results_summary.json",
    ]:
        print("  -", outdir / p)


if __name__ == "__main__":
    main()
