# -*- coding: utf-8 -*-
"""
MPR-1: MultiProjection Reconstruction Audit

Purpose
-------
Reuses TCD-1/TCD-2 feature outputs to test whether a combined projection
reconstructs a richer latent structure S than any single projection:

    S = (O, R_topo, B_binding, P_priority, D_dyn, Gamma)

Core tests:
1. Coarse mechanism recovery
2. Submechanism recovery
3. Direction binding tasks: source C/E, closure update C/E
4. GenError prediction
5. Same-answer internal structure split
6. Ablation: TopK-only, Binding/Priority-only, Dynamics-only, TopK+Dynamics,
   TopK+Binding, Binding+Dynamics, MultiProjection, AnswerOrthogonal variants

Default paths are written for the user's local Windows setup.
"""

import os
import json
import math
import warnings
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
)
from sklearn.model_selection import GroupKFold, StratifiedKFold
from sklearn.exceptions import ConvergenceWarning

warnings.filterwarnings("ignore", category=ConvergenceWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------
TCD1_OUT_DIR = r"C:\Users\ZH\Desktop\AGI\outputs\tcd1_outputs"
TCD2_OUT_DIR = r"C:\Users\ZH\Desktop\AGI\outputs\tcd2_outputs"
OUT_DIR = r"C:\Users\ZH\Desktop\AGI\outputs\mpr1_outputs"

FEATURES_PATH = os.path.join(TCD1_OUT_DIR, "tcd1_features.csv")
DATASET_PATH = os.path.join(TCD1_OUT_DIR, "tcd1_dataset.csv")

RANDOM_SEED = 42
N_SPLITS = 5
EPS = 1e-9

# -----------------------------------------------------------------------------
# Utility
# -----------------------------------------------------------------------------
def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def safe_float(x, default=np.nan):
    try:
        if x is None:
            return default
        v = float(x)
        if math.isfinite(v):
            return v
        return default
    except Exception:
        return default


def numeric_cols(df: pd.DataFrame, cols: List[str]) -> List[str]:
    out = []
    for c in cols:
        if c in df.columns and pd.api.types.is_numeric_dtype(df[c]):
            if df[c].notna().sum() > 0:
                out.append(c)
    return out


def infer_feature_groups(df: pd.DataFrame) -> Dict[str, List[str]]:
    """Infer feature groups from column names generated by TCD-1.

    The previous scripts used broad names. This function is deliberately permissive.
    """
    non_feature = {
        "row_id", "prompt", "answer", "gen", "gen_label", "mechanism",
        "mechanism_group", "submechanism", "condition", "graph_id",
        "surface_id", "pair_id", "topic", "relation", "target", "clean_answer",
        "conflict_answer", "label_C", "label_E", "is_error", "gen_error",
    }
    all_num = [c for c in df.columns if c not in non_feature and pd.api.types.is_numeric_dtype(df[c])]

    def has_any(c: str, keys: List[str]) -> bool:
        cl = c.lower()
        return any(k in cl for k in keys)

    topk = [c for c in all_num if has_any(c, ["topk", "vim", "jaccard", "center", "spread", "entropy"])]
    init_topk = [c for c in topk if has_any(c, ["init", "l0", "l1", "l2", "l3", "l4", "l5", "l6"])]
    main_topk = [c for c in topk if has_any(c, ["20", "21", "22", "23", "24", "25", "main", "decision"])]

    answer = [c for c in all_num if has_any(c, ["margin", "rank", "logit", "answer", "c_minus_e", "c_e", "ce_"])]
    # Avoid swallowing all trajectory variables with "margin" only; kept as explicit answer baseline.

    dyn = [c for c in all_num if has_any(c, ["delta", "deltau", "du", "slope", "area", "curv", "db", "hshape", "traj", "residual", "detour", "oper", "ocont", "perp", "boundary", "crossing"])]

    # Binding / priority / non-topk structural projections.
    binding = [c for c in all_num if has_any(c, ["closure", "logic", "contrad", "source", "trusted", "priority", "rule", "old", "new", "binding", "chain", "consistency", "probe"])]

    # Remove topk and direct answer from binding if names overlap.
    binding = [c for c in binding if c not in set(topk) and c not in set(answer)]
    dyn_clean = [c for c in dyn if c not in set(topk)]

    topk_plus_dyn = sorted(set(topk + dyn_clean))
    topk_plus_binding = sorted(set(topk + binding))
    binding_plus_dyn = sorted(set(binding + dyn_clean))
    multiproj = sorted(set(topk + binding + dyn_clean))

    groups = {
        "TopK_init_only": numeric_cols(df, init_topk),
        "TopK_main_only": numeric_cols(df, main_topk),
        "TopK_all": numeric_cols(df, topk),
        "Answer_margin": numeric_cols(df, answer),
        "BindingPriority_only": numeric_cols(df, binding),
        "Dynamics_only": numeric_cols(df, dyn_clean),
        "TopK_plus_Dynamics": numeric_cols(df, topk_plus_dyn),
        "TopK_plus_BindingPriority": numeric_cols(df, topk_plus_binding),
        "BindingPriority_plus_Dynamics": numeric_cols(df, binding_plus_dyn),
        "MultiProjection": numeric_cols(df, multiproj),
    }
    return {k: v for k, v in groups.items() if len(v) > 0}


def fill_X(df: pd.DataFrame, cols: List[str]) -> np.ndarray:
    X = df[cols].copy()
    X = X.replace([np.inf, -np.inf], np.nan)
    for c in cols:
        med = X[c].median(skipna=True)
        if not np.isfinite(med):
            med = 0.0
        X[c] = X[c].fillna(med)
    return X.values.astype(np.float64)


def make_clf(binary: bool = False):
    return make_pipeline(
        StandardScaler(),
        LogisticRegression(
            max_iter=3000,
            solver="lbfgs",
            class_weight="balanced",
            random_state=RANDOM_SEED,
        ),
    )


def eval_binary(df: pd.DataFrame, cols: List[str], target: str, group_col: str = "graph_id") -> Dict:
    if target not in df.columns or len(cols) == 0:
        return {"valid": False, "reason": "missing_target_or_features"}
    y = df[target].astype(int).values
    if len(np.unique(y)) < 2:
        return {"valid": False, "reason": "single_class"}
    X = fill_X(df, cols)
    groups = df[group_col].astype(str).values if group_col in df.columns else np.arange(len(df))
    n_groups = len(np.unique(groups))
    n_splits = min(N_SPLITS, n_groups)
    if n_splits < 2:
        cv = StratifiedKFold(n_splits=min(N_SPLITS, np.bincount(y).min()), shuffle=True, random_state=RANDOM_SEED)
        split_iter = cv.split(X, y)
    else:
        cv = GroupKFold(n_splits=n_splits)
        split_iter = cv.split(X, y, groups)

    prob = np.full(len(df), np.nan)
    pred = np.full(len(df), -1)
    for train_idx, test_idx in split_iter:
        if len(np.unique(y[train_idx])) < 2:
            continue
        clf = make_clf(binary=True)
        clf.fit(X[train_idx], y[train_idx])
        if hasattr(clf[-1], "predict_proba"):
            p = clf.predict_proba(X[test_idx])[:, 1]
        else:
            p = clf.decision_function(X[test_idx])
        prob[test_idx] = p
        pred[test_idx] = (p >= 0.5).astype(int)

    mask = np.isfinite(prob) & (pred >= 0)
    if mask.sum() == 0 or len(np.unique(y[mask])) < 2:
        return {"valid": False, "reason": "no_valid_folds"}
    return {
        "valid": True,
        "auc": float(roc_auc_score(y[mask], prob[mask])),
        "acc": float(accuracy_score(y[mask], pred[mask])),
        "f1": float(f1_score(y[mask], pred[mask], zero_division=0)),
        "bal_acc": float(balanced_accuracy_score(y[mask], pred[mask])),
        "n": int(mask.sum()),
    }


def eval_multiclass(df: pd.DataFrame, cols: List[str], target: str, group_col: str = "graph_id") -> Dict:
    if target not in df.columns or len(cols) == 0:
        return {"valid": False, "reason": "missing_target_or_features"}
    y_raw = df[target].astype(str).values
    if len(np.unique(y_raw)) < 2:
        return {"valid": False, "reason": "single_class"}
    le = LabelEncoder()
    y = le.fit_transform(y_raw)
    X = fill_X(df, cols)
    groups = df[group_col].astype(str).values if group_col in df.columns else np.arange(len(df))
    n_groups = len(np.unique(groups))
    n_splits = min(N_SPLITS, n_groups)
    if n_splits < 2:
        cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_SEED)
        split_iter = cv.split(X, y)
    else:
        cv = GroupKFold(n_splits=n_splits)
        split_iter = cv.split(X, y, groups)

    pred = np.full(len(df), -1)
    for train_idx, test_idx in split_iter:
        if len(np.unique(y[train_idx])) < 2:
            continue
        clf = make_clf(binary=False)
        clf.fit(X[train_idx], y[train_idx])
        pred[test_idx] = clf.predict(X[test_idx])

    mask = pred >= 0
    if mask.sum() == 0:
        return {"valid": False, "reason": "no_valid_folds"}
    return {
        "valid": True,
        "acc": float(accuracy_score(y[mask], pred[mask])),
        "macro_f1": float(f1_score(y[mask], pred[mask], average="macro", zero_division=0)),
        "weighted_f1": float(f1_score(y[mask], pred[mask], average="weighted", zero_division=0)),
        "bal_acc": float(balanced_accuracy_score(y[mask], pred[mask])),
        "n": int(mask.sum()),
        "classes": list(le.classes_),
    }


def answer_orthogonalize(df: pd.DataFrame, feature_cols: List[str], answer_cols: List[str]) -> pd.DataFrame:
    """Residualize feature columns against answer columns using least squares."""
    if not feature_cols or not answer_cols:
        return df.copy()
    usable_answer = numeric_cols(df, answer_cols)
    if not usable_answer:
        return df.copy()

    out = df.copy()
    A = fill_X(df, usable_answer)
    A = np.column_stack([np.ones(A.shape[0]), A])
    for c in feature_cols:
        y = fill_X(df, [c]).reshape(-1)
        try:
            beta, *_ = np.linalg.lstsq(A, y, rcond=None)
            resid = y - A @ beta
            out[c] = resid
        except Exception:
            pass
    return out


def run_direction_task(df: pd.DataFrame, groups: Dict[str, List[str]], task_name: str, labels: Tuple[str, str], target_col: str = "submechanism") -> List[Dict]:
    a, b = labels
    sub = df[df[target_col].astype(str).isin([a, b])].copy()
    if len(sub) < 20:
        return []
    sub["direction_y"] = (sub[target_col].astype(str) == b).astype(int)
    rows = []
    for gname, cols in groups.items():
        res = eval_binary(sub, cols, target="direction_y", group_col="graph_id")
        row = {"task": task_name, "feature_group": gname, "n_features": len(cols)}
        row.update(res)
        rows.append(row)
    return rows


def same_answer_split(df: pd.DataFrame, groups: Dict[str, List[str]]) -> List[Dict]:
    # Use MultiProjection to test whether submechanism remains recoverable within same generated answer.
    cols = groups.get("MultiProjection", [])
    if not cols:
        return []
    ans_col = "gen_label" if "gen_label" in df.columns else ("gen" if "gen" in df.columns else "answer")
    if ans_col not in df.columns or "submechanism" not in df.columns:
        return []
    rows = []
    for ans, sub in df.groupby(ans_col):
        if len(sub) < 40 or sub["submechanism"].nunique() < 2:
            continue
        res = eval_multiclass(sub, cols, target="submechanism", group_col="graph_id")
        row = {"answer": str(ans), "n_rows": int(len(sub)), "feature_group": "MultiProjection"}
        row.update(res)
        rows.append(row)
    return rows


def main():
    ensure_dir(OUT_DIR)
    if not os.path.exists(FEATURES_PATH):
        raise FileNotFoundError(f"Missing features file: {FEATURES_PATH}")
    df = pd.read_csv(FEATURES_PATH)
    if df.empty:
        verdict = {"verdict": "FAIL_EMPTY_FEATURES", "features_path": FEATURES_PATH}
        with open(os.path.join(OUT_DIR, "mpr1_verdict.json"), "w", encoding="utf-8") as f:
            json.dump(verdict, f, ensure_ascii=False, indent=2)
        print(json.dumps(verdict, ensure_ascii=False, indent=2))
        return

    # Harmonize target names.
    if "mechanism_group" not in df.columns and "mechanism" in df.columns:
        df["mechanism_group"] = df["mechanism"]
    if "gen_error" not in df.columns:
        if "gen_label" in df.columns:
            df["gen_error"] = (df["gen_label"].astype(str) == "E").astype(int)
        elif "gen" in df.columns:
            df["gen_error"] = (df["gen"].astype(str) == "E").astype(int)

    groups = infer_feature_groups(df)
    if not groups:
        verdict = {"verdict": "FAIL_NO_FEATURE_GROUPS", "n_cols": len(df.columns)}
        with open(os.path.join(OUT_DIR, "mpr1_verdict.json"), "w", encoding="utf-8") as f:
            json.dump(verdict, f, ensure_ascii=False, indent=2)
        print(json.dumps(verdict, ensure_ascii=False, indent=2))
        return

    # Answer-orthogonal groups.
    answer_cols = groups.get("Answer_margin", [])
    full_cols = groups.get("MultiProjection", [])
    topk_cols = groups.get("TopK_all", [])
    binding_cols = groups.get("BindingPriority_only", [])
    dyn_cols = groups.get("Dynamics_only", [])

    orth_df = answer_orthogonalize(df, sorted(set(full_cols + topk_cols + binding_cols + dyn_cols)), answer_cols)
    orth_groups = {}
    for name, cols in groups.items():
        if name == "Answer_margin":
            continue
        orth_groups[name + "__orth"] = cols

    rows = []
    # Core targets.
    for gname, cols in groups.items():
        if "mechanism_group" in df.columns:
            r = {"target": "mechanism_group", "feature_group": gname, "n_features": len(cols)}
            r.update(eval_multiclass(df, cols, "mechanism_group", "graph_id"))
            rows.append(r)
        if "submechanism" in df.columns:
            r = {"target": "submechanism", "feature_group": gname, "n_features": len(cols)}
            r.update(eval_multiclass(df, cols, "submechanism", "graph_id"))
            rows.append(r)
        if "gen_error" in df.columns and df["gen_error"].nunique() >= 2:
            r = {"target": "gen_error", "feature_group": gname, "n_features": len(cols)}
            r.update(eval_binary(df, cols, "gen_error", "graph_id"))
            rows.append(r)

    for gname, cols in orth_groups.items():
        if "mechanism_group" in orth_df.columns:
            r = {"target": "mechanism_group", "feature_group": gname, "n_features": len(cols)}
            r.update(eval_multiclass(orth_df, cols, "mechanism_group", "graph_id"))
            rows.append(r)
        if "submechanism" in orth_df.columns:
            r = {"target": "submechanism", "feature_group": gname, "n_features": len(cols)}
            r.update(eval_multiclass(orth_df, cols, "submechanism", "graph_id"))
            rows.append(r)
        if "gen_error" in orth_df.columns and orth_df["gen_error"].nunique() >= 2:
            r = {"target": "gen_error", "feature_group": gname, "n_features": len(cols)}
            r.update(eval_binary(orth_df, cols, "gen_error", "graph_id"))
            rows.append(r)

    model_summary = pd.DataFrame(rows)
    model_summary.to_csv(os.path.join(OUT_DIR, "mpr1_model_summary.csv"), index=False, encoding="utf-8-sig")

    # Direction tasks.
    direction_rows = []
    if "submechanism" in df.columns:
        direction_rows += run_direction_task(df, groups, "source_binding_C_vs_E", ("competition_source_C", "competition_source_E"))
        direction_rows += run_direction_task(df, groups, "closure_update_C_vs_E", ("closure_update_C", "closure_update_E"))
        direction_rows += run_direction_task(orth_df, orth_groups, "source_binding_C_vs_E_orth", ("competition_source_C", "competition_source_E"))
        direction_rows += run_direction_task(orth_df, orth_groups, "closure_update_C_vs_E_orth", ("closure_update_C", "closure_update_E"))
    direction_summary = pd.DataFrame(direction_rows)
    direction_summary.to_csv(os.path.join(OUT_DIR, "mpr1_direction_summary.csv"), index=False, encoding="utf-8-sig")

    # Same answer split.
    same_rows = same_answer_split(df, groups)
    with open(os.path.join(OUT_DIR, "mpr1_same_answer_split_summary.json"), "w", encoding="utf-8") as f:
        json.dump(same_rows, f, ensure_ascii=False, indent=2)

    # Extract key metrics.
    def get_metric(target, group, metric):
        if model_summary.empty:
            return np.nan
        sub = model_summary[(model_summary["target"] == target) & (model_summary["feature_group"] == group)]
        if len(sub) == 0 or metric not in sub.columns:
            return np.nan
        return safe_float(sub.iloc[0].get(metric))

    topk_mech = get_metric("mechanism_group", "TopK_all", "macro_f1")
    mp_mech = get_metric("mechanism_group", "MultiProjection", "macro_f1")
    topk_sub = get_metric("submechanism", "TopK_all", "macro_f1")
    mp_sub = get_metric("submechanism", "MultiProjection", "macro_f1")
    topk_sub_orth = get_metric("submechanism", "TopK_all__orth", "macro_f1")
    mp_sub_orth = get_metric("submechanism", "MultiProjection__orth", "macro_f1")
    topk_gen = get_metric("gen_error", "TopK_all", "auc")
    mp_gen = get_metric("gen_error", "MultiProjection", "auc")
    answer_gen = get_metric("gen_error", "Answer_margin", "auc")

    verdict_reasons = []
    verdict = "PARTIAL_MPR_UNCLEAR"

    if np.isfinite(mp_sub) and np.isfinite(topk_sub) and mp_sub > topk_sub + 0.05:
        verdict_reasons.append("MultiProjection improves submechanism recovery over TopK-only.")
    if np.isfinite(mp_sub_orth) and np.isfinite(topk_sub_orth) and mp_sub_orth > topk_sub_orth + 0.05:
        verdict_reasons.append("Answer-orthogonal MultiProjection improves submechanism recovery over answer-orthogonal TopK.")
    if np.isfinite(mp_gen) and np.isfinite(topk_gen) and mp_gen > topk_gen + 0.03:
        verdict_reasons.append("MultiProjection improves GenError prediction over TopK-only.")
    if np.isfinite(mp_mech) and np.isfinite(topk_mech) and abs(mp_mech - topk_mech) < 0.03:
        verdict_reasons.append("TopK already preserves coarse mechanism topology.")

    same_pass = False
    if same_rows:
        vals = [r.get("macro_f1", np.nan) for r in same_rows if r.get("valid", False)]
        vals = [v for v in vals if np.isfinite(v)]
        if vals and float(np.nanmean(vals)) > 0.55:
            same_pass = True
            verdict_reasons.append("Same-answer internal submechanism split remains recoverable.")

    if any("submechanism" in r for r in verdict_reasons) and same_pass:
        verdict = "PASS_MPR_RECONSTRUCTION_STRONG"
    elif any("submechanism" in r for r in verdict_reasons):
        verdict = "PASS_MPR_SUBMECHANISM_STRONG"
    elif np.isfinite(mp_gen) and np.isfinite(answer_gen) and mp_gen > answer_gen + 0.03:
        verdict = "PASS_MPR_GENERROR_ONLY"
    else:
        verdict = "PARTIAL_OR_FAIL_MPR_NO_CLEAR_GAIN"

    verdict_json = {
        "verdict": verdict,
        "reasons": verdict_reasons,
        "metrics": {
            "topk_mechanism_macro_f1": topk_mech,
            "multiprojection_mechanism_macro_f1": mp_mech,
            "topk_submechanism_macro_f1": topk_sub,
            "multiprojection_submechanism_macro_f1": mp_sub,
            "answer_orthogonal_topk_submechanism_macro_f1": topk_sub_orth,
            "answer_orthogonal_multiprojection_submechanism_macro_f1": mp_sub_orth,
            "topk_gen_auc": topk_gen,
            "multiprojection_gen_auc": mp_gen,
            "answer_margin_gen_auc": answer_gen,
        },
        "feature_set_sizes": {k: len(v) for k, v in groups.items()},
        "n_rows": int(len(df)),
        "n_graphs": int(df["graph_id"].nunique()) if "graph_id" in df.columns else None,
        "conditions": sorted(df["condition"].astype(str).unique().tolist()) if "condition" in df.columns else [],
        "submechanisms": sorted(df["submechanism"].astype(str).unique().tolist()) if "submechanism" in df.columns else [],
    }
    with open(os.path.join(OUT_DIR, "mpr1_verdict.json"), "w", encoding="utf-8") as f:
        json.dump(verdict_json, f, ensure_ascii=False, indent=2)

    print(json.dumps(verdict_json, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
