# -*- coding: utf-8 -*-
r"""
SOB-V1A: Derivative Constraint Visibility Audit

Purpose
-------
Validate whether Constraint Visibility V(S,O) is a measurable subject-object
coupling variable.

Core hypothesis
---------------
For the same object O = Derivative, different subject states S_k should show
a measurable visibility gradient:

    V(S0,O) < V(S1,O) < V(S2,O) < V(S3,O) < V(S4,O)

where:

    S0 = symbol-only exposure
    S1 = definition knowledge
    S2 = calculation ability
    S3 = geometric understanding
    S4 = cross-domain transfer ability

Visibility observable
---------------------
V = w_C*C + w_T*T + w_CF*CF + w_CP*CP + w_E*E

C   = Closure
T   = Transfer
CF  = Counterfactual
CP  = Compression
E   = Error-boundary / edge-case visibility

This script evaluates generated answers using:
1. answer text generated by each local model;
2. a deterministic rubric based on expected constraint markers;
3. monotonicity and dimension-wise gradient tests.

Default output
--------------
C:\Users\ZH\Desktop\AGI\outputs\SOB-V1A

Default models
--------------
Qwen:
  D:\model\models--Qwen--Qwen2.5-1.5B-Instruct\main

Llama:
  D:\model\Llama-3.2-1B-Instruct

Gemma:
  D:\model\gemma-2-2b-it

Notes
-----
This is the first SOB experiment. It is deliberately text-output based,
because SOB-V1A is testing subject-state induced constraint visibility,
not hidden-state dynamics yet.

The next experiment can add hidden-state / TopK visibility probes.
"""

import os
import re
import json
import time
import math
import traceback
import warnings
from pathlib import Path
from collections import defaultdict

import numpy as np
import pandas as pd
import torch

from transformers import AutoTokenizer, AutoModelForCausalLM

warnings.filterwarnings("ignore", category=UserWarning)

# ============================================================
# Constants
# ============================================================

EXPERIMENT_ID = "SOB-V1A"
OUT_DIR = Path(r"C:\Users\ZH\Desktop\AGI\outputs\SOB-V1A")
OUT_DIR.mkdir(parents=True, exist_ok=True)

MODEL_SPECS = {
    "qwen": {
        "model_name": "Qwen2.5-1.5B-Instruct",
        "path": r"D:\model\models--Qwen--Qwen2.5-1.5B-Instruct\main",
        "trust_remote_code": True,
    },
    "llama": {
        "model_name": "Llama-3.2-1B-Instruct",
        "path": r"D:\model\Llama-3.2-1B-Instruct",
        "trust_remote_code": True,
    },
    "gemma": {
        "model_name": "gemma-2-2b-it",
        "path": r"D:\model\gemma-2-2b-it",
        "trust_remote_code": True,
    },
}

MODELS_TO_RUN = ["qwen", "llama", "gemma"]

RANDOM_SEED = 42
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE = torch.float16 if torch.cuda.is_available() else torch.float32

MAX_INPUT_LEN = 1024
MAX_NEW_TOKENS = 220
TEMPERATURE = 0.0
DO_SAMPLE = False

SUBJECT_STATES = [
    {
        "state_id": "S0",
        "state_rank": 0,
        "state_name": "symbol_only",
        "profile": (
            "You are a learner who has only seen the symbol d/dx and f'(x). "
            "You do not know the formal definition, calculation rules, geometry, or applications. "
            "Answer strictly from this limited state. Do not pretend to know more."
        ),
    },
    {
        "state_id": "S1",
        "state_rank": 1,
        "state_name": "definition_known",
        "profile": (
            "You are a learner who knows the formal definition of derivative as a limit. "
            "You know that it measures instantaneous rate of change, but you are not yet fluent at calculation, geometry, or cross-domain transfer."
        ),
    },
    {
        "state_id": "S2",
        "state_rank": 2,
        "state_name": "calculation_ability",
        "profile": (
            "You are a learner who can compute derivatives using standard rules such as power, product, quotient, and chain rule. "
            "You know the definition, but your geometric and cross-domain understanding is still limited."
        ),
    },
    {
        "state_id": "S3",
        "state_rank": 3,
        "state_name": "geometric_understanding",
        "profile": (
            "You are a learner who understands the derivative geometrically as tangent slope and local linear approximation. "
            "You can connect definition, computation, and geometry, but cross-domain transfer is not yet expert-level."
        ),
    },
    {
        "state_id": "S4",
        "state_rank": 4,
        "state_name": "cross_domain_transfer",
        "profile": (
            "You are an expert learner who can transfer derivative across mathematics, physics, optimization, machine learning, and control. "
            "You understand definition, computation, geometry, counterfactuals, edge cases, and unifying compression."
        ),
    },
]

TASKS = [
    {
        "task_id": "C1_closure_graph",
        "dimension": "C",
        "question": (
            "Explain the derivative by connecting these ideas into one concept map: limit, instantaneous rate of change, tangent slope, local linear approximation, and function change."
        ),
    },
    {
        "task_id": "C2_relation_disambiguation",
        "dimension": "C",
        "question": (
            "Are 'slope of a secant line', 'slope of a tangent line', and 'derivative' the same thing? Explain their relationship clearly."
        ),
    },
    {
        "task_id": "T1_physics_transfer",
        "dimension": "T",
        "question": (
            "Transfer the idea of derivative to physics. Explain how position, velocity, and acceleration are related through derivatives."
        ),
    },
    {
        "task_id": "T2_optimization_ml_transfer",
        "dimension": "T",
        "question": (
            "Transfer the idea of derivative to optimization and machine learning. Explain why gradients matter in gradient descent or backpropagation."
        ),
    },
    {
        "task_id": "CF1_nonexistent_derivative",
        "dimension": "CF",
        "question": (
            "What would break in mathematics or applications if derivatives did not exist or if local change could not be defined?"
        ),
    },
    {
        "task_id": "CF2_counterfactual_smoothness",
        "dimension": "CF",
        "question": (
            "If a function is continuous everywhere, must it be differentiable everywhere? Explain with a counterexample or boundary case."
        ),
    },
    {
        "task_id": "CP1_unified_short_explanation",
        "dimension": "CP",
        "question": (
            "Give the shortest unified explanation you can: what is a derivative, and why do the limit definition, tangent slope, rate of change, and local linear approximation all describe the same object?"
        ),
    },
    {
        "task_id": "CP2_minimal_variables",
        "dimension": "CP",
        "question": (
            "Explain derivative using as few core variables or primitives as possible, while still preserving its meaning."
        ),
    },
    {
        "task_id": "E1_abs_x_edge",
        "dimension": "E",
        "question": (
            "Why is f(x)=|x| not differentiable at x=0, even though it is continuous there?"
        ),
    },
    {
        "task_id": "E2_continuity_differentiability_boundary",
        "dimension": "E",
        "question": (
            "Why does differentiability imply continuity, but continuity does not imply differentiability?"
        ),
    },
]

DIM_WEIGHTS = {
    "C": 0.25,
    "T": 0.20,
    "CF": 0.20,
    "CP": 0.20,
    "E": 0.15,
}

EXPECTED_MARKERS = {
    "C": [
        "limit", "instantaneous", "rate", "tangent", "slope", "local", "linear",
        "approximation", "secant", "approaches", "change", "function"
    ],
    "T": [
        "velocity", "acceleration", "position", "time", "gradient", "descent",
        "optimization", "machine learning", "backpropagation", "loss", "parameter",
        "control", "feedback"
    ],
    "CF": [
        "not exist", "would break", "cannot", "no local", "counterexample",
        "continuous", "not differentiable", "corner", "cusp", "smooth", "assumption",
        "boundary"
    ],
    "CP": [
        "local linear", "best linear", "first-order", "rate of change", "slope",
        "limit", "unifies", "same object", "minimal", "core", "compression"
    ],
    "E": [
        "absolute value", "|x|", "left derivative", "right derivative", "not equal",
        "corner", "continuous", "differentiable", "implies continuity",
        "continuity does not imply", "cusp", "vertical tangent"
    ],
}

NEGATIVE_MARKERS = {
    "S0": ["chain rule", "gradient descent", "backpropagation", "local linear approximation", "left derivative", "right derivative"],
    "S1": ["backpropagation", "control theory", "jacobian", "hessian"],
    "S2": ["manifold", "frechet", "functional derivative"],
}

# ============================================================
# Utilities
# ============================================================

def set_seed(seed=RANDOM_SEED):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def now_time():
    return time.strftime("%Y-%m-%d %H:%M:%S")


def safe_float(x, default=np.nan):
    try:
        if x is None:
            return default
        if isinstance(x, (float, int, np.floating, np.integer)):
            return float(x)
        return float(str(x))
    except Exception:
        return default


def safe_mean(xs):
    arr = np.asarray([safe_float(x) for x in xs], dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return np.nan
    return float(arr.mean())


def normalize_text(s):
    s = str(s).lower()
    s = s.replace("’", "'").replace("“", '"').replace("”", '"')
    return s


def count_words(s):
    return len(re.findall(r"\b[\w'-]+\b", str(s)))


def marker_score(text, markers):
    t = normalize_text(text)
    if not markers:
        return 0.0, 0, []
    hits = []
    for m in markers:
        if normalize_text(m) in t:
            hits.append(m)
    score = len(set(hits)) / max(1, len(markers))
    return float(min(1.0, score)), len(set(hits)), sorted(set(hits))


def lexical_diversity(text):
    words = re.findall(r"\b[a-zA-Z][a-zA-Z'-]*\b", normalize_text(text))
    if not words:
        return 0.0
    return float(len(set(words)) / max(1, len(words)))


def compression_bonus(text):
    n = count_words(text)
    if n <= 0:
        return 0.0
    if 35 <= n <= 120:
        return 1.0
    if n < 35:
        return max(0.0, n / 35.0)
    return max(0.0, 1.0 - (n - 120) / 260.0)


def overclaim_penalty(text, state_id):
    t = normalize_text(text)
    markers = NEGATIVE_MARKERS.get(state_id, [])
    hits = [m for m in markers if normalize_text(m) in t]
    if not hits:
        return 0.0, []
    return min(0.35, 0.08 * len(set(hits))), sorted(set(hits))


def score_answer(row):
    text = row.get("answer_text", "")
    dim = row.get("dimension", "")
    state_id = row.get("state_id", "")

    base, hit_count, hits = marker_score(text, EXPECTED_MARKERS.get(dim, []))
    word_n = count_words(text)
    div = lexical_diversity(text)
    cb = compression_bonus(text) if dim == "CP" else 0.0
    penalty, penalty_hits = overclaim_penalty(text, state_id)

    length_quality = 0.0
    if word_n > 10:
        length_quality = min(1.0, math.log1p(word_n) / math.log1p(120))

    if dim == "CP":
        score = 0.68 * base + 0.22 * cb + 0.10 * div
    else:
        score = 0.78 * base + 0.12 * length_quality + 0.10 * div

    score = max(0.0, min(1.0, score - penalty))

    return {
        "rubric_score": score,
        "marker_score": base,
        "marker_hit_count": hit_count,
        "marker_hits": "; ".join(hits),
        "word_count": word_n,
        "lexical_diversity": div,
        "compression_bonus": cb,
        "overclaim_penalty": penalty,
        "overclaim_hits": "; ".join(penalty_hits),
    }


def build_prompt(subject_state, task):
    return (
        "You are participating in a cognitive science audit.\n\n"
        "Important instruction:\n"
        "Answer only from the learner state described below. Do not exceed that state.\n\n"
        f"Learner state:\n{subject_state['profile']}\n\n"
        "Object of cognition: derivative.\n\n"
        f"Task:\n{task['question']}\n\n"
        "Write a concise answer in English. Do not mention this audit or the learner state."
    )


def build_dataset():
    rows = []
    for st in SUBJECT_STATES:
        for task in TASKS:
            rows.append({
                "row_id": len(rows),
                "state_id": st["state_id"],
                "state_rank": st["state_rank"],
                "state_name": st["state_name"],
                "dimension": task["dimension"],
                "task_id": task["task_id"],
                "question": task["question"],
                "prompt": build_prompt(st, task),
            })
    return pd.DataFrame(rows)


def format_chat(tokenizer, prompt):
    if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
        try:
            return tokenizer.apply_chat_template(
                [{"role": "user", "content": prompt}],
                tokenize=False,
                add_generation_prompt=True,
            )
        except Exception:
            return prompt
    return prompt


def load_model_and_tokenizer(path, trust_remote_code=True):
    tokenizer = AutoTokenizer.from_pretrained(
        path,
        trust_remote_code=trust_remote_code,
        local_files_only=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        path,
        trust_remote_code=trust_remote_code,
        local_files_only=True,
        torch_dtype=DTYPE,
        device_map=None,
    )
    model.to(DEVICE)
    model.eval()
    return model, tokenizer


@torch.no_grad()
def generate_answer(model, tokenizer, prompt):
    text = format_chat(tokenizer, prompt)
    enc = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_INPUT_LEN,
    )
    enc = {k: v.to(DEVICE) for k, v in enc.items()}

    gen_kwargs = {
        "max_new_tokens": MAX_NEW_TOKENS,
        "do_sample": DO_SAMPLE,
        "temperature": TEMPERATURE,
        "pad_token_id": tokenizer.pad_token_id,
        "eos_token_id": tokenizer.eos_token_id,
    }

    if not DO_SAMPLE:
        gen_kwargs.pop("temperature", None)

    out = model.generate(**enc, **gen_kwargs)
    new_tokens = out[0, enc["input_ids"].shape[1]:]
    ans = tokenizer.decode(new_tokens, skip_special_tokens=True)
    return ans.strip()


def evaluate_visibility(answer_df):
    scored = []
    for _, row in answer_df.iterrows():
        d = row.to_dict()
        d.update(score_answer(d))
        scored.append(d)
    scored_df = pd.DataFrame(scored)

    # Dimension score per state.
    dim_summary = (
        scored_df
        .groupby(["model_key", "state_id", "state_rank", "state_name", "dimension"], as_index=False)
        .agg(
            dimension_score=("rubric_score", "mean"),
            marker_score=("marker_score", "mean"),
            word_count=("word_count", "mean"),
            n=("rubric_score", "size"),
        )
    )

    rows = []
    for (model_key, state_id, state_rank, state_name), sub in dim_summary.groupby(["model_key", "state_id", "state_rank", "state_name"]):
        score_by_dim = {r["dimension"]: safe_float(r["dimension_score"]) for _, r in sub.iterrows()}
        v = 0.0
        for dim, w in DIM_WEIGHTS.items():
            v += w * score_by_dim.get(dim, 0.0)
        row = {
            "model_key": model_key,
            "state_id": state_id,
            "state_rank": int(state_rank),
            "state_name": state_name,
            "V_total": float(v),
        }
        for dim in DIM_WEIGHTS:
            row[f"V_{dim}"] = score_by_dim.get(dim, np.nan)
        rows.append(row)

    visibility = pd.DataFrame(rows).sort_values(["model_key", "state_rank"])

    verdicts = []
    for model_key, sub in visibility.groupby("model_key"):
        sub = sub.sort_values("state_rank")
        vals = sub["V_total"].values.astype(float)
        diffs = np.diff(vals)

        strict_mono = bool(np.all(diffs > 0))
        nondecreasing = bool(np.all(diffs >= -1e-9))
        spearman = np.nan
        pearson = np.nan
        if len(vals) >= 2 and np.std(vals) > 1e-12:
            ranks = sub["state_rank"].values.astype(float)
            pearson = float(np.corrcoef(ranks, vals)[0, 1])
            order_vals = pd.Series(vals).rank().values
            spearman = float(np.corrcoef(ranks, order_vals)[0, 1])

        dim_mono = {}
        for dim in DIM_WEIGHTS:
            dvals = sub[f"V_{dim}"].values.astype(float)
            if len(dvals) >= 2:
                dim_mono[dim] = bool(np.all(np.diff(dvals) >= -1e-9))
            else:
                dim_mono[dim] = False

        if strict_mono and pearson >= 0.90:
            verdict = "PASS_STRONG_VISIBILITY_GRADIENT"
        elif nondecreasing and pearson >= 0.80:
            verdict = "PASS_VISIBILITY_GRADIENT"
        elif pearson >= 0.60:
            verdict = "PARTIAL_VISIBILITY_GRADIENT"
        else:
            verdict = "FAIL_VISIBILITY_GRADIENT"

        verdicts.append({
            "model_key": model_key,
            "verdict": verdict,
            "strict_monotonic": strict_mono,
            "nondecreasing": nondecreasing,
            "pearson_state_V": pearson,
            "spearman_state_V": spearman,
            "V_S0": safe_float(sub[sub["state_id"] == "S0"]["V_total"].iloc[0]) if (sub["state_id"] == "S0").any() else np.nan,
            "V_S1": safe_float(sub[sub["state_id"] == "S1"]["V_total"].iloc[0]) if (sub["state_id"] == "S1").any() else np.nan,
            "V_S2": safe_float(sub[sub["state_id"] == "S2"]["V_total"].iloc[0]) if (sub["state_id"] == "S2").any() else np.nan,
            "V_S3": safe_float(sub[sub["state_id"] == "S3"]["V_total"].iloc[0]) if (sub["state_id"] == "S3").any() else np.nan,
            "V_S4": safe_float(sub[sub["state_id"] == "S4"]["V_total"].iloc[0]) if (sub["state_id"] == "S4").any() else np.nan,
            "diffs": ";".join([f"{x:.6f}" for x in diffs]),
            "dim_monotonic_json": json.dumps(dim_mono, ensure_ascii=False),
        })

    verdict_df = pd.DataFrame(verdicts)

    return scored_df, dim_summary, visibility, verdict_df


def run_one_model(model_key, dataset):
    spec = MODEL_SPECS[model_key]
    model_out = OUT_DIR / model_key
    model_out.mkdir(parents=True, exist_ok=True)

    info = {
        "experiment_id": EXPERIMENT_ID,
        "model_key": model_key,
        "model_name": spec["model_name"],
        "path": spec["path"],
        "exists": os.path.exists(spec["path"]),
        "status": "pending",
        "started_at": now_time(),
    }

    if not os.path.exists(spec["path"]):
        info.update({
            "status": "missing_path",
            "error": f"Path not found: {spec['path']}",
        })
        return info

    model = None
    try:
        t0 = time.time()
        model, tokenizer = load_model_and_tokenizer(spec["path"], spec.get("trust_remote_code", True))

        rows = []
        errors = []

        for i, row in dataset.iterrows():
            if i % 10 == 0:
                print(f"[{model_key}] generating row {i}/{len(dataset)}", flush=True)
            try:
                ans = generate_answer(model, tokenizer, row["prompt"])
                rows.append({
                    **row.to_dict(),
                    "model_key": model_key,
                    "model_name": spec["model_name"],
                    "answer_text": ans,
                })
            except Exception as e:
                errors.append({
                    "row_id": int(row["row_id"]),
                    "state_id": row["state_id"],
                    "task_id": row["task_id"],
                    "error_type": type(e).__name__,
                    "error": str(e),
                    "traceback": traceback.format_exc(),
                })
                print(f"[warn][{model_key}] row {row['row_id']} failed: {type(e).__name__}: {e}", flush=True)

        answer_df = pd.DataFrame(rows)
        error_df = pd.DataFrame(errors)

        answer_df.to_csv(model_out / f"{EXPERIMENT_ID}_{model_key}_answers.csv", index=False, encoding="utf-8-sig")
        error_df.to_csv(model_out / f"{EXPERIMENT_ID}_{model_key}_errors.csv", index=False, encoding="utf-8-sig")

        if answer_df.empty:
            info.update({
                "status": "empty_answers",
                "n_errors": int(len(error_df)),
            })
            return info

        scored_df, dim_summary, visibility, verdict_df = evaluate_visibility(answer_df)

        scored_df.to_csv(model_out / f"{EXPERIMENT_ID}_{model_key}_scored_answers.csv", index=False, encoding="utf-8-sig")
        dim_summary.to_csv(model_out / f"{EXPERIMENT_ID}_{model_key}_dimension_summary.csv", index=False, encoding="utf-8-sig")
        visibility.to_csv(model_out / f"{EXPERIMENT_ID}_{model_key}_visibility_summary.csv", index=False, encoding="utf-8-sig")
        verdict_df.to_csv(model_out / f"{EXPERIMENT_ID}_{model_key}_verdict_summary.csv", index=False, encoding="utf-8-sig")

        verdict = verdict_df.iloc[0].to_dict() if len(verdict_df) else {}
        info.update({
            "status": "done",
            "finished_at": now_time(),
            "runtime_sec": time.time() - t0,
            "n_rows": int(len(answer_df)),
            "n_errors": int(len(error_df)),
            "verdict": verdict.get("verdict", "UNDETERMINED"),
            "metrics": verdict,
            "outputs": {
                "answers": str(model_out / f"{EXPERIMENT_ID}_{model_key}_answers.csv"),
                "scored_answers": str(model_out / f"{EXPERIMENT_ID}_{model_key}_scored_answers.csv"),
                "dimension_summary": str(model_out / f"{EXPERIMENT_ID}_{model_key}_dimension_summary.csv"),
                "visibility_summary": str(model_out / f"{EXPERIMENT_ID}_{model_key}_visibility_summary.csv"),
                "verdict_summary": str(model_out / f"{EXPERIMENT_ID}_{model_key}_verdict_summary.csv"),
            },
        })

        with open(model_out / f"{EXPERIMENT_ID}_{model_key}_verdict.json", "w", encoding="utf-8") as f:
            json.dump(info, f, ensure_ascii=False, indent=2)

    except Exception as e:
        info.update({
            "status": "failed",
            "finished_at": now_time(),
            "error_type": type(e).__name__,
            "error": str(e),
            "traceback": traceback.format_exc(),
        })

    finally:
        try:
            del model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        except Exception:
            pass

    return info


def cross_model_summary(model_infos):
    rows = []
    for info in model_infos:
        m = info.get("metrics", {}) or {}
        rows.append({
            "model_key": info.get("model_key"),
            "model_name": info.get("model_name"),
            "status": info.get("status"),
            "verdict": info.get("verdict"),
            "strict_monotonic": m.get("strict_monotonic"),
            "nondecreasing": m.get("nondecreasing"),
            "pearson_state_V": m.get("pearson_state_V"),
            "spearman_state_V": m.get("spearman_state_V"),
            "V_S0": m.get("V_S0"),
            "V_S1": m.get("V_S1"),
            "V_S2": m.get("V_S2"),
            "V_S3": m.get("V_S3"),
            "V_S4": m.get("V_S4"),
            "diffs": m.get("diffs"),
            "n_rows": info.get("n_rows"),
            "n_errors": info.get("n_errors"),
            "error": info.get("error"),
        })
    return pd.DataFrame(rows)


def global_verdict(cross):
    done = cross[cross["status"] == "done"].copy()
    if len(done) == 0:
        return "FAIL_SOBV1A_NO_MODELS"

    verdicts = done["verdict"].astype(str).tolist()
    pass_strong = sum(v.startswith("PASS_STRONG") for v in verdicts)
    pass_any = sum(v.startswith("PASS") for v in verdicts)
    partial = sum(v.startswith("PARTIAL") for v in verdicts)

    if pass_strong == len(done):
        return "PASS_STRONG_SOBV1A_CROSS_MODEL"
    if pass_any == len(done):
        return "PASS_SOBV1A_CROSS_MODEL"
    if pass_any + partial == len(done):
        return "PARTIAL_SOBV1A_CROSS_MODEL"
    if pass_any >= 1:
        return "MIXED_SOBV1A"
    return "FAIL_SOBV1A"


def main():
    set_seed()
    print("=" * 80)
    print(f"[{EXPERIMENT_ID}] Starting Derivative Constraint Visibility Audit")
    print(f"Device: {DEVICE}, dtype: {DTYPE}")
    print(f"Output: {OUT_DIR}")
    print("=" * 80)

    dataset = build_dataset()
    dataset_path = OUT_DIR / f"{EXPERIMENT_ID}_dataset.csv"
    dataset.to_csv(dataset_path, index=False, encoding="utf-8-sig")

    config = {
        "experiment_id": EXPERIMENT_ID,
        "created_at": now_time(),
        "out_dir": str(OUT_DIR),
        "device": DEVICE,
        "dtype": str(DTYPE),
        "models_to_run": MODELS_TO_RUN,
        "model_specs": MODEL_SPECS,
        "subject_states": SUBJECT_STATES,
        "tasks": TASKS,
        "dimension_weights": DIM_WEIGHTS,
        "max_input_len": MAX_INPUT_LEN,
        "max_new_tokens": MAX_NEW_TOKENS,
        "temperature": TEMPERATURE,
        "do_sample": DO_SAMPLE,
        "random_seed": RANDOM_SEED,
    }
    with open(OUT_DIR / f"{EXPERIMENT_ID}_config.json", "w", encoding="utf-8") as f:
        json.dump(config, f, ensure_ascii=False, indent=2)

    model_infos = []
    for model_key in MODELS_TO_RUN:
        print("=" * 80)
        print(f"[{EXPERIMENT_ID}] Running model: {model_key}")
        info = run_one_model(model_key, dataset)
        model_infos.append(info)
        print(json.dumps({
            "model_key": info.get("model_key"),
            "status": info.get("status"),
            "verdict": info.get("verdict"),
            "metrics": info.get("metrics"),
            "error": info.get("error"),
        }, ensure_ascii=False, indent=2))

    cross = cross_model_summary(model_infos)
    cross_path = OUT_DIR / f"{EXPERIMENT_ID}_cross_model_summary.csv"
    cross.to_csv(cross_path, index=False, encoding="utf-8-sig")

    gv = global_verdict(cross)
    global_obj = {
        "experiment_id": EXPERIMENT_ID,
        "verdict": gv,
        "n_models": len(model_infos),
        "n_models_done": int((cross["status"] == "done").sum()) if "status" in cross.columns else 0,
        "model_infos": model_infos,
        "outputs": {
            "dataset": str(dataset_path),
            "cross_model_summary": str(cross_path),
            "out_dir": str(OUT_DIR),
        },
        "interpretation": {
            "PASS_STRONG_VISIBILITY_GRADIENT": "V(S,O) strictly increases from S0 to S4 with strong state-rank correlation.",
            "PASS_VISIBILITY_GRADIENT": "V(S,O) nondecreasingly increases from S0 to S4 with strong state-rank correlation.",
            "PARTIAL_VISIBILITY_GRADIENT": "V(S,O) has a positive state-rank relation but is not cleanly monotonic.",
            "FAIL_VISIBILITY_GRADIENT": "No stable visibility gradient detected.",
        },
    }

    with open(OUT_DIR / f"{EXPERIMENT_ID}_verdict.json", "w", encoding="utf-8") as f:
        json.dump(global_obj, f, ensure_ascii=False, indent=2)

    print("=" * 80)
    print(json.dumps(global_obj, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
